import { test, expect } from '@playwright/test'

test('guest landing, registration and personal journal work across devices',async({page,browser},info)=>{
  const email=`browser-${info.project.name}-${Date.now()}@example.test`,password='Тестовая парольная фраза 2026!'
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Твоё тело. Каждый день.'})).toBeVisible()
  await page.getByRole('link',{name:'Начать сегодня'}).click()
  await page.getByLabel('Как тебя зовут').fill('Тестовый пользователь')
  await page.getByLabel('Email',{exact:true}).fill(email)
  await page.getByLabel('Пароль',{exact:true}).fill(password)
  await page.getByRole('checkbox').check()
  await page.getByRole('button',{name:'Создать аккаунт',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Сохрани резервный код'})).toBeVisible()
  await expect(page.locator('.recovery-code')).not.toBeEmpty()
  await page.getByLabel('Я сохранил резервный код').check()
  await page.getByRole('button',{name:'Перейти в кабинет'}).click()
  await expect(page.getByRole('heading',{name:'Мой день',exact:true})).toBeVisible()
  const navigate=async(name:string)=>{if(info.project.name==='mobile')await page.getByRole('button',{name:'Открыть меню',exact:true}).click();await page.getByRole('navigation').getByRole('button',{name,exact:true}).click()}
  await page.getByRole('button',{name:'Записать вес',exact:true}).first().click()
  await page.getByLabel('Вес, кг',{exact:true}).fill('72.5')
  await page.getByRole('dialog').getByRole('button',{name:'Сохранить',exact:true}).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByRole('button',{name:/Последняя запись веса/})).toContainText('72,5 кг')
  await page.getByRole('button',{name:'Вода: не выполнено',exact:true}).click()
  await expect(page.getByRole('button',{name:'Вода: выполнено',exact:true})).toHaveAttribute('aria-pressed','true')
  await navigate('Питание')
  await page.getByRole('button',{name:'Свой продукт',exact:true}).click()
  await page.getByRole('dialog').getByLabel('Название',{exact:true}).fill('Тестовые хлопья')
  await page.getByLabel('Калории, ккал',{exact:true}).fill('200')
  await page.getByLabel('Белки, г',{exact:true}).fill('10')
  await page.getByLabel('Жиры, г',{exact:true}).fill('5')
  await page.getByLabel('Углеводы, г',{exact:true}).fill('25')
  await page.getByLabel('Источник значений',{exact:true}).fill('Этикетка для теста')
  await page.getByRole('dialog').getByRole('button',{name:'Сохранить',exact:true}).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button',{name:'Продукты',exact:true}).click()
  await page.getByRole('textbox',{name:'Найти в каталоге'}).fill('Тестовые хлопья')
  await page.getByRole('button',{name:'В мой день',exact:true}).click()
  await page.getByLabel('Порции по 100 г').fill('1.5')
  await page.getByLabel('Уже съедено').check()
  await page.getByRole('button',{name:'Сохранить приём пищи'}).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.locator('.real-macros')).toContainText('300')
  await navigate('Покупки')
  await page.getByRole('button',{name:'Обновить из плана'}).click()
  await expect(page.getByRole('button',{name:'Тестовые хлопья: купить',exact:true})).toBeVisible()
  await expect(page.locator('.shopping-row')).toContainText('150 г')
  await page.getByRole('button',{name:'Тестовые хлопья: купить',exact:true}).click()
  await expect(page.getByRole('button',{name:'Тестовые хлопья: куплено',exact:true})).toHaveAttribute('aria-pressed','true')
  await navigate('Тренировки')
  await page.getByRole('button',{name:'Добавить занятие',exact:true}).click()
  await page.getByRole('button',{name:'Продолжить',exact:true}).click()
  for(const box of await page.getByRole('dialog').getByRole('checkbox',{name:'Готово',exact:true}).all())await box.check()
  await page.getByLabel('Завершить тренировку').check()
  await page.getByRole('button',{name:'Сохранить тренировку'}).click()
  await expect(page.locator('.workout-log')).toContainText('Завершена')
  await navigate('Мой день')
  await page.screenshot({path:`artifacts/account-${info.project.name}.png`,fullPage:true,animations:'disabled'})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  const phone=await browser.newContext(),other=await phone.newPage()
  await other.goto('http://127.0.0.1:5173/login')
  await other.getByLabel('Email',{exact:true}).fill(email)
  await other.getByLabel('Пароль',{exact:true}).fill(password)
  await other.getByRole('button',{name:'Войти',exact:true}).click()
  await expect(other.getByRole('button',{name:/Последняя запись веса/})).toContainText('72,5 кг')
  await expect(other.getByRole('button',{name:'Вода: выполнено',exact:true})).toHaveAttribute('aria-pressed','true')
  await phone.close()
  expect(errors).toEqual([])
})

test('signed-out user is redirected, landing has no overflow',async({page})=>{
  await page.goto('/app');await expect(page).toHaveURL(/\/login$/)
  await page.goto('/');await page.evaluate(()=>document.fonts.ready)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await page.goto('/privacy');await expect(page.getByRole('heading',{name:'Как мы обращаемся с данными',exact:true})).toBeVisible()
})
