"""Reusable, deliberately conservative Blender helpers for TELO365 exercise clips.

The helpers validate an already authored action.  They never infer motion from an
exercise name and never edit the canonical character armature or mesh.
Run inside Blender 5.2+ after opening a dedicated animation working file.
"""

from pathlib import Path
import bpy

CANONICAL_BONES = (
    'Hips', 'Spine', 'Chest', 'Neck', 'Head',
    'LeftUpperArm', 'LeftLowerArm', 'LeftHand',
    'RightUpperArm', 'RightLowerArm', 'RightHand',
    'LeftUpperLeg', 'LeftLowerLeg', 'LeftFoot', 'LeftToe',
    'RightUpperLeg', 'RightLowerLeg', 'RightFoot', 'RightToe',
)

def assert_canonical_rig(rig):
    """Ensure an animation file still uses the known deform-rig topology."""
    if rig is None or rig.type != 'ARMATURE':
        raise RuntimeError('Expected an Armature object for the TELO365 trainer rig.')
    names = {bone.name for bone in rig.data.bones}
    missing = [name for name in CANONICAL_BONES if name not in names]
    extra = sorted(names - set(CANONICAL_BONES))
    if missing or extra:
        raise RuntimeError(f'Canonical rig mismatch. Missing={missing}; unexpected={extra}')
    return rig

def _fcurves(action):
    """Support actions exported by current Blender and older action layouts."""
    if action.fcurves:
        return list(action.fcurves)
    curves = []
    for layer in getattr(action, 'layers', []):
        for strip in getattr(layer, 'strips', []):
            for channelbag in getattr(strip, 'channelbags', []):
                curves.extend(channelbag.fcurves)
    return curves

def assert_authored_action(action, clip_name):
    if action is None:
        raise RuntimeError('An authored animation Action is required; no movement is generated by this pipeline.')
    if action.name != clip_name:
        raise RuntimeError(f'Expected Action named {clip_name!r}, got {action.name!r}.')
    curves = _fcurves(action)
    if not curves:
        raise RuntimeError('Action has no F-curves. Author real key poses before export.')
    if not any('pose.bones["Hips"]' in curve.data_path for curve in curves):
        raise RuntimeError('Action does not animate Hips; inspect the authored movement and root policy.')
    return curves

def assert_loop(action, tolerance=1e-5):
    """Compare the first and final keyed value for every animated channel."""
    for curve in _fcurves(action):
        points = curve.keyframe_points
        if len(points) < 2:
            continue
        if abs(points[0].co[1] - points[-1].co[1]) > tolerance:
            raise RuntimeError(f'Loop boundary differs: {curve.data_path}[{curve.array_index}]')

def export_animation_glb(rig, action, output_path, clip_name):
    """Export the selected rig and one authored action to a separate GLB clip.

    Do not call this against a canonical rig working file.  Work in a copied
    animation scene and retain that .blend next to the exported clip.
    """
    assert_canonical_rig(rig)
    assert_authored_action(action, clip_name)
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    bpy.ops.object.select_all(action='DESELECT')
    rig.select_set(True)
    bpy.context.view_layer.objects.active = rig
    if rig.animation_data is None:
        rig.animation_data_create()
    rig.animation_data.action = action
    bpy.ops.export_scene.gltf(
        filepath=str(output),
        export_format='GLB',
        use_selection=True,
        export_animations=True,
        export_force_sampling=True,
        export_nla_strips=False,
        export_all_actions=False,
        export_frame_range=True,
        export_yup=True,
    )
    return output
