import { useEffect, useState } from 'react'
import { api, type CatalogItem, type Mutate, type State } from '../api'
import { Dialog, ErrorMessage, errorText, Title } from './ui'
import CatalogEditor from './CatalogEditor'
export default function Admin({data,mutate}:{data:State;mutate:Mutate}){
  const [status,setStatus]=useState<{users:number;healthy:boolean;intro:string}|null>(null),[error,setError]=useState(''),[kind,setKind]=useState('food'),[editing,setEditing]=useState<CatalogItem|undefined>(),[open,setOpen]=useState(false),[busy,setBusy]=useState(false)
  useEffect(()=>{api<{users:number;healthy:boolean;intro:string}>('/api/admin/status').then(setStatus).catch(e=>setError(errorText(e)))},[])
  const labels:Record<string,string>={food:'Продукты',recipe:'Рецепты',exercise:'Упражнения',program:'Программы'}
  return <div className="journal-grid"><section className="card"><Title>Сервис</Title><ErrorMessage error={error}/>{status&&<><p className="admin-summary">Аккаунтов: {status.users} · База: {status.healthy?'проверка пройдена':'требует проверки'}</p><form className="workspace-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await mutate('/api/admin/intro','PUT',{intro:new FormData(e.currentTarget).get('intro')})}catch(e){setError(errorText(e))}finally{setBusy(false)}}}><label>Описание на главной<textarea name="intro" defaultValue={status.intro} required maxLength={600} rows={5}/></label><button className="primary-button" disabled={busy}>Обновить описание</button></form></>}</section><section className="card"><Title action={()=>{setEditing(undefined);setOpen(true)}}>Общий каталог</Title><div className="tabs">{Object.entries(labels).map(([key,label])=><button className={kind===key?'selected':''} key={key} onClick={()=>setKind(key)}>{label}</button>)}</div>{data.catalog.filter(i=>!i.owner&&i.kind===kind).map(i=><button key={i.id} className="admin-item" onClick={()=>{setEditing(i);setOpen(true)}}><strong>{i.name}</strong><span>Редактировать →</span></button>)}</section>{open&&<Dialog title={editing?'Редактировать запись':'Новая запись'} close={()=>setOpen(false)}><CatalogEditor kind={kind} item={editing} shared catalog={data.catalog} mutate={mutate} done={()=>setOpen(false)}/></Dialog>}</div>
}
