import { useState } from 'react'
import { type CatalogItem, type Mutate } from '../api'
import { ErrorMessage, errorText } from './ui'
export default function CatalogEditor({kind,catalog,item,shared=false,mutate,done}:{kind:string;catalog:CatalogItem[];item?:CatalogItem;shared?:boolean;mutate:Mutate;done:()=>void}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false)
  const foods=catalog.filter(i=>i.kind==='food'&&(!shared||!i.owner)),exercises=catalog.filter(i=>i.kind==='exercise'&&(!shared||!i.owner))
  const [ingredients,setIngredients]=useState(item?.ingredients||[{foodId:foods[0]?.id||'',grams:100}])
  const [program,setProgram]=useState(item?.exercises||[{exerciseId:exercises[0]?.id||'',sets:3,reps:12,weight:0}])
  return <form className="workspace-form" onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);const f=new FormData(e.currentTarget),body:Record<string,unknown>={kind,name:f.get('name')};if(kind==='food'){for(const k of ['kcal','p','f','c'])body[k]=Number(f.get(k));body.source=f.get('source')}if(kind==='recipe')Object.assign(body,{ingredients,instructions:f.get('instructions'),image:f.get('image')});if(kind==='exercise')Object.assign(body,{muscle:f.get('muscle'),description:f.get('description'),unit:f.get('unit')});if(kind==='program')Object.assign(body,{description:f.get('description'),minutes:Number(f.get('minutes')),exercises:program});try{await mutate((shared?'/api/admin/catalog':'/api/catalog')+(item?'/'+item.id:''),item?'PUT':'POST',body);done()}catch(e){setError(errorText(e))}finally{setBusy(false)}}}>
    <label>Название<input name="name" defaultValue={item?.name} maxLength={120} required/></label>
    {kind==='food'&&<><p className="form-note">Значения на 100 г продукта. Перенеси их с упаковки или из выбранного справочника.</p><div className="form-grid">{[['kcal','Калории, ккал'],['p','Белки, г'],['f','Жиры, г'],['c','Углеводы, г']].map(([key,label])=><label key={key}>{label}<input name={key} type="number" min={0} max={key==='kcal'?1000:100} step="0.1" defaultValue={item?.[key as 'kcal']??0} required/></label>)}</div><label>Источник значений<input name="source" placeholder="Например: упаковка, название марки" defaultValue={item?.source} maxLength={500} required/></label></>}
    {kind==='recipe'&&<><p className="form-note">Ингредиенты на одну порцию. Пищевая ценность рассчитается из продуктов.</p>{ingredients.map((ingredient,i)=><div className="ingredient-row" key={i}><label>Продукт {i+1}<select value={ingredient.foodId} required onChange={e=>setIngredients(rows=>rows.map((v,n)=>n===i?{...v,foodId:e.target.value}:v))}>{foods.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><label>Граммы<input type="number" min={1} max={10000} value={ingredient.grams} onChange={e=>setIngredients(rows=>rows.map((v,n)=>n===i?{...v,grams:Number(e.target.value)}:v))} required/></label><button type="button" className="text-button danger" disabled={ingredients.length===1} aria-label={`Удалить ингредиент ${i+1}`} onClick={()=>setIngredients(rows=>rows.filter((_,n)=>n!==i))}>×</button></div>)}<button type="button" className="soft-button" disabled={ingredients.length>=30||!foods.length} onClick={()=>setIngredients(rows=>[...rows,{foodId:foods[0].id,grams:100}])}>Добавить ингредиент</button><label>Приготовление<textarea name="instructions" defaultValue={item?.instructions} maxLength={4000} required rows={4}/></label><label>Иллюстрация<select name="image" defaultValue={item?.image||'lunch'}><option value="breakfast">Завтрак</option><option value="lunch">Обед</option><option value="dinner">Ужин</option><option value="snack">Перекус</option></select></label></>}
    {kind==='exercise'&&<><label>Группа мышц<input name="muscle" defaultValue={item?.muscle} maxLength={100} required/></label><label>Описание<textarea name="description" defaultValue={item?.description} maxLength={4000} required rows={4}/></label><label>Единица учёта<select name="unit" defaultValue={item?.unit||'reps'}><option value="reps">Повторения</option><option value="seconds">Секунды</option></select></label></>}
    {kind==='program'&&<><label>Описание<textarea name="description" defaultValue={item?.description} maxLength={4000} required/></label><label>Длительность, минут<input type="number" name="minutes" defaultValue={item?.minutes||45} min={1} max={600} required/></label>{program.map((p,i)=><div className="program-editor" key={i}><label>Упражнение {i+1}<select required value={p.exerciseId} onChange={e=>setProgram(rows=>rows.map((v,n)=>n===i?{...v,exerciseId:e.target.value}:v))}>{exercises.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><div className="form-grid">{[['sets','Подходы',20],['reps','Повторы / секунды',600],['weight','Вес, кг',500]].map(([key,label,max])=><label key={key}>{label}<input type="number" min={key==='weight'?0:1} max={max} step={key==='weight'?0.5:1} value={p[key as 'sets']} onChange={e=>setProgram(rows=>rows.map((v,n)=>n===i?{...v,[key]:Number(e.target.value)}:v))}/></label>)}</div><button type="button" className="text-button danger" disabled={program.length===1} onClick={()=>setProgram(rows=>rows.filter((_,n)=>n!==i))}>Убрать упражнение</button></div>)}<button type="button" className="soft-button" disabled={program.length>=20||!exercises.length} onClick={()=>setProgram(rows=>[...rows,{exerciseId:exercises[0].id,sets:3,reps:12,weight:0}])}>Добавить упражнение</button></>}
    <ErrorMessage error={error}/><button className="primary-button" disabled={busy}>{busy?'Сохраняем…':'Сохранить'}</button>
  </form>
}
