import { useCallback, useEffect, useRef, useState } from 'react'
import { Activity, ArrowRight, Check, ChevronLeft, ChevronRight, Droplets, Flag, Heart, House, LogOut, Menu, Plus, RefreshCw, Settings, ShoppingCart, UserRound, Utensils, Weight } from 'lucide-react'
import { api, ApiError, fmt, type State, type Mutate } from '../api'
import { Dialog, Empty, ErrorMessage, errorText, Logo, Title } from './ui'
import Profile from './Profile'
import Nutrition from './Nutrition'
import Workouts from './Workouts'
import Shopping from './Shopping'
import Admin from './Admin'
import Habits from './Habits'
import HeroVideoBackground from './HeroVideoBackground'

const displayDate=(value:string)=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`))
const shortDate=(value:string)=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`)).replace('.','')
const navigation=[['home','Мой день',House],['nutrition','Питание',Utensils],['workouts','Тренировки',Activity],['progress','Прогресс',Weight],['habits','Привычки',Heart],['shopping','Покупки',ShoppingCart],['profile','Профиль',UserRound]] as const
export default function Dashboard(){
  const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[selectedDate,setDate]=useState(''),[section,setSection]=useState('home'),[menu,setMenu]=useState(false),[dialog,setDialog]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[weightPeriod,setWeightPeriod]=useState<'7'|'30'|'90'|'all'>('30')
  const seq=useRef(0),pending=useRef(false)
  const refresh=useCallback(async()=>{const request=++seq.current;try{const next=await api<State>('/api/state'+(selectedDate?`?date=${selectedDate}`:''));if(request===seq.current){setData(next);setError('')}}catch(e){if(e instanceof ApiError&&e.status===401)location.assign('/login');if(request===seq.current)setError(errorText(e));throw e}},[selectedDate])
  useEffect(()=>{refresh().catch(()=>{});const timer=setInterval(()=>{if(!pending.current&&document.visibilityState==='visible')refresh().catch(()=>{})},20000);const focus=()=>{if(!pending.current)refresh().catch(()=>{})};window.addEventListener('focus',focus);return()=>{seq.current++;clearInterval(timer);window.removeEventListener('focus',focus)}},[refresh])
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(timer)},[notice])
  useEffect(()=>{if(data&&!data.user.onboardingCompleted)location.replace('/onboarding')},[data])

  const mutate:Mutate=async(path,method,body)=>{if(pending.current)throw new Error('Дождитесь сохранения предыдущего изменения');pending.current=true;setBusy(true);setError('');try{await api(path,method,body);await refresh();setNotice('Сохранено')}catch(e){setError(errorText(e));throw e}finally{pending.current=false;setBusy(false)}}
  const execute=(path:string,method:string,body?:unknown)=>mutate(path,method,body).catch(()=>{})
  if(!data)return <div className="loading-page"><Logo/><p>{error||'Открываем твой день…'}</p>{error&&<button className="primary-button" onClick={()=>refresh().catch(()=>{})}>Повторить</button>}</div>
  const day=data.date,weightsForDay=data.weights.filter(w=>w.date<=day),latest=weightsForDay.at(-1),previous=weightsForDay.at(-2),first=weightsForDay[0]
  const nutrition=data.meals.filter(m=>m.eaten).reduce((sum,m)=>({kcal:sum.kcal+m.snapshot.kcal*m.servings,p:sum.p+m.snapshot.p*m.servings,f:sum.f+m.snapshot.f*m.servings,c:sum.c+m.snapshot.c*m.servings}),{kcal:0,p:0,f:0,c:0})
  const goalDetail=data.user.goal==='maintain'&&data.user.targetLow!=null&&data.user.targetHigh!=null?`Комфортный вес: ${fmt(data.user.targetLow)}–${fmt(data.user.targetHigh)} кг`:data.user.target?`Целевой вес: ${fmt(data.user.target)} кг`:'В своём темпе'
  const weightDays=weightPeriod==='7'?7:weightPeriod==='30'?30:weightPeriod==='90'?90:Infinity,weightHistory=weightPeriod==='all'||!latest?weightsForDay:weightsForDay.filter(weight=>Date.parse(weight.date)>=Date.parse(latest.date)-weightDays*86400000)
  function navigate(next:string){setSection(next);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})}
  function changeDay(offset:number){const next=new Date(day+'T12:00:00Z');next.setUTCDate(next.getUTCDate()+offset);setDate(next.toISOString().slice(0,10))}
  return <div className="app-shell workspace">
    {menu&&<button className="menu-scrim" aria-label="Закрыть меню" onClick={()=>setMenu(false)}/>}
    <aside className={`sidebar ${menu?'is-open':''}`}><a className="brand-link" href="/"><Logo/><span className="brand-caption">ТВОЙ ЛИЧНЫЙ РИТМ</span></a><nav aria-label="Основная навигация">{navigation.map(([id,name,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>navigate(id)}><Icon size={21}/>{name}</button>)}{data.user.role==='admin'&&<button className={section==='admin'?'active':''} onClick={()=>navigate('admin')}><Settings size={21}/>Управление</button>}</nav><div className="workspace-side-note"><Heart size={24}/><p>Не идеальный день.<br/>Твой настоящий день.</p></div><button className="logout-button" onClick={()=>{api('/api/auth/logout','POST',{}).then(()=>location.assign('/')).catch(e=>setError(errorText(e)))}}><LogOut size={17}/>Выйти</button></aside>
    <main><header className="topbar"><button className="icon-button mobile-menu" aria-label="Открыть меню" onClick={()=>setMenu(true)}><Menu/></button><span className="workspace-greeting">Привет, <strong>{data.user.name}</strong></span><div className="day-control"><button className="icon-button" aria-label="Предыдущий день" onClick={()=>changeDay(-1)}><ChevronLeft size={17}/></button><input type="date" aria-label="Дата дневника" value={day} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/><button className="icon-button" aria-label="Следующий день" onClick={()=>changeDay(1)}><ChevronRight size={17}/></button><button className="text-button" onClick={()=>setDate('')}>Сегодня</button></div><button className="icon-button" aria-label="Обновить данные" onClick={()=>refresh().catch(()=>{})}><RefreshCw size={18}/></button></header>
    <div className="page-content"><div className="page-heading"><div><span className="eyebrow">ЗАБОТА О СЕБЕ КАЖДЫЙ ДЕНЬ</span><h1>{navigation.find(n=>n[0]===section)?.[1]||'Управление сервисом'}</h1></div><span className="sync-status">{busy?'Сохраняем…':'Записи в твоём аккаунте'}</span></div><ErrorMessage error={error}/>
    {section==='home'&&<><section className="hero workspace-hero">
        <HeroVideoBackground/>
        <div className="hero-content"><span className="eyebrow">МАЛЕНЬКИЕ ШАГИ · НАСТОЯЩИЙ ПРОГРЕСС</span><h2>В своём ритме.<br/>Каждый день.</h2><p>Сегодня — ещё одна возможность позаботиться о себе.</p><button className="primary-button" onClick={()=>setDialog('quick-add')}><Plus size={17}/>Добавить запись</button></div></section><div className="overview-stats"><button className="card" onClick={()=>setDialog('weight')}><Weight/><span>Последняя запись веса<strong>{latest?`${fmt(latest.value)} кг`:'Пока нет записи'}</strong><small>{latest?`${displayDate(latest.date)}${previous?` · ${previous.value===latest.value?'0':`${latest.value>previous.value?'+':''}${fmt(latest.value-previous.value)}`} кг к прошлой записи`:''}`:'Добавь первую запись'}</small></span></button><button className="card" onClick={()=>navigate('profile')}><Flag/><span>Твоя цель<strong>{({wellbeing:'Поддерживать форму',lose:'Снижение веса',gain:'Набор веса',maintain:'Поддерживать форму'} as Record<string,string>)[data.user.goal]}</strong><small>{goalDetail}</small></span></button><button className="card calorie-summary" onClick={()=>navigate('nutrition')}><Utensils/><span>Съедено за день<strong>{Math.round(nutrition.kcal).toLocaleString('ru-RU')}{data.user.calories?` / ${Math.round(data.user.calories).toLocaleString('ru-RU')}`:''} ккал</strong>{data.user.calories&&<i className="calorie-progress"><b style={{width:`${Math.min(100,Math.round(nutrition.kcal/data.user.calories*100))}%`}}/></i>}<small>Б {Math.round(nutrition.p)} г · Ж {Math.round(nutrition.f)} г · У {Math.round(nutrition.c)} г</small></span></button></div></>}
    {['home','progress','habits'].includes(section)&&<div className="journal-grid">
      {section!=='habits'&&<section className={`card ${latest?'':'weight-empty'}`}><Title action={()=>setDialog('weight')} label="Записать вес">История веса</Title>{weightsForDay.length?<><WeightChart values={weightHistory} period={weightPeriod} onPeriodChange={setWeightPeriod}/>{first&&latest&&<p className="history-delta">За всё время: {latest.value-first.value>0?'+':''}{fmt(latest.value-first.value)} кг</p>}<div className="weight-history">{weightHistory.slice(-7).reverse().map(w=><div key={w.date}><span>{displayDate(w.date)}</span><strong>{fmt(w.value)} кг</strong><details className="weight-row-menu"><summary aria-label={`Действия для записи веса ${w.date}`}>⋯</summary><div><button className="text-button" onClick={()=>{setDate(w.date);setDialog('weight')}}>Изменить</button><button className="text-button danger" disabled={busy} onClick={()=>execute('/api/weights','DELETE',{date:w.date})}>Удалить</button></div></details></div>)}</div></>:<Empty action={()=>setDialog('weight')} label="Записать вес">Добавь первую запись. Здесь появится твоя история.</Empty>}</section>}
      {section!=='progress'&&<Habits data={data} mutate={mutate} busy={busy} full={section==='habits'}/>}    </div>}
    {section==='home'&&<div className="home-shortcuts">{[['nutrition','Питание',`${data.meals.length} записей · ${Math.round(nutrition.kcal).toLocaleString('ru-RU')}${data.user.calories?` / ${Math.round(data.user.calories).toLocaleString('ru-RU')}`:''} ккал`],['workouts','Тренировки',data.workouts.filter(w=>w.date===day).length?`${data.workouts.filter(w=>w.date===day).length} занят. сегодня`:'На сегодня нет занятия'],['shopping','Покупки',`${data.shopping.filter(s=>!s.checked).length} товаров в списке`]].map(([id,label,text])=><button className="card" key={id} onClick={()=>navigate(id)}><span><strong>{label}</strong><small>{text}</small></span><ArrowRight size={20}/></button>)}</div>}
    {section==='nutrition'&&<Nutrition data={data} mutate={mutate} busy={busy}/>}{section==='workouts'&&<Workouts data={data} mutate={mutate} busy={busy}/>}{section==='shopping'&&<Shopping data={data} mutate={mutate} busy={busy}/>}{section==='profile'&&<Profile user={data.user} mutate={mutate} busy={busy}/>}{section==='admin'&&data.user.role==='admin'&&<Admin data={data} mutate={mutate}/>}
    <footer className="page-footer"><span>TELO365 · Твой личный ритм</span><a href="/privacy">О данных и доступе</a></footer></div></main>
    {notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
    {dialog==='quick-add'&&<Dialog title="Добавить запись" close={()=>setDialog('')}><p className="dialog-intro">Выбери то, что хочешь отметить сейчас.</p><div className="quick-add-grid"><button onClick={()=>setDialog('weight')}><span className="round-icon green"><Weight size={19}/></span><span><strong>Вес</strong><small>Записать текущий вес</small></span><ArrowRight size={16}/></button><button onClick={()=>{setDialog('');navigate('nutrition')}}><span className="round-icon yellow"><Utensils size={19}/></span><span><strong>Приём пищи</strong><small>Добавить еду или напиток</small></span><ArrowRight size={16}/></button><button onClick={()=>{setDialog('');navigate('habits')}}><span className="round-icon blue"><Droplets size={19}/></span><span><strong>Вода и привычки</strong><small>Отметить свой ритм</small></span><ArrowRight size={16}/></button><button onClick={()=>{setDialog('');navigate('workouts')}}><span className="round-icon purple"><Activity size={19}/></span><span><strong>Тренировка</strong><small>Открыть план занятия</small></span><ArrowRight size={16}/></button></div></Dialog>}    {dialog==='weight'&&<Dialog title="Запись веса" close={()=>setDialog('')}><form className="workspace-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await mutate('/api/weights','PUT',{date:f.get('date'),value:Number(f.get('value'))});setDialog('')}catch{}}}><label>Дата<input name="date" type="date" defaultValue={day>data.today?data.today:day} max={data.today} required/></label><label>Вес, кг<input name="value" type="number" min={30} max={350} step="0.1" defaultValue={data.weights.find(w=>w.date===day)?.value} required autoFocus/></label><p className="form-note">Одна запись на дату. Повторное сохранение обновит её.</p><ErrorMessage error={error}/><button className="primary-button" disabled={busy}>Сохранить</button></form></Dialog>}

  </div>
}
function WeightChart({values,period,onPeriodChange}:{values:{date:string;value:number}[];period:'7'|'30'|'90'|'all';onPeriodChange:(period:'7'|'30'|'90'|'all')=>void}){
  const chartValues=values,low=Math.min(...chartValues.map(v=>v.value))-1,high=Math.max(...chartValues.map(v=>v.value))+1,start=Date.parse(chartValues[0].date),end=Date.parse(chartValues.at(-1)!.date),delta=chartValues.at(-1)!.value-chartValues[0].value
  const x=(date:string)=>end===start?180:45+(Date.parse(date)-start)/(end-start)*290,y=(value:number)=>145-(value-low)/(high-low||1)*120
  return <><div className="weight-range"><div>{(['7','30','90','all'] as const).map(value=><button key={value} className={period===value?'selected':''} onClick={()=>onPeriodChange(value)}>{value==='all'?'Всё':value==='90'?'3 мес':`${value} дней`}</button>)}</div><strong className={delta>0?'up':delta<0?'down':''}>{delta===0?'Изменение за период: 0 кг':`Изменение за период: ${delta>0?'+':''}${fmt(delta)} кг`}</strong></div><svg className="real-chart" viewBox="0 0 365 185" role="img" aria-label="График записей веса">{[0,1,2,3].map(i=><g key={i}><line x1="40" x2="340" y1={25+i*40} y2={25+i*40} stroke="#e9eee6"/><text x="2" y={29+i*40}>{fmt(high-(high-low)*i/3)}</text></g>)}<polyline points={chartValues.map(v=>`${x(v.date)},${y(v.value)}`).join(' ')} fill="none" stroke="#528345" strokeWidth="2.5"/>{chartValues.map(v=><circle key={v.date} cx={x(v.date)} cy={y(v.value)} r="4" fill="#528345" stroke="white"><title>{v.date}: {fmt(v.value)} кг</title></circle>)}<text x="45" y="175">{shortDate(chartValues[0].date)}</text><text x="335" y="175" textAnchor="end">{chartValues.length>1?shortDate(chartValues.at(-1)!.date):''}</text></svg></>
}