import { useCallback, useEffect, useRef, useState } from 'react'
import { Activity, ArrowRight, Check, ChevronLeft, ChevronRight, Flag, Heart, House, LogOut, Menu, Plus, RefreshCw, Settings, ShoppingCart, UserRound, Utensils, Weight } from 'lucide-react'
import { api, ApiError, fmt, type State, type Mutate } from '../api'
import { Dialog, Empty, ErrorMessage, errorText, Logo, Title } from './ui'
import Profile from './Profile'
import Nutrition from './Nutrition'
import Workouts from './Workouts'
import Shopping from './Shopping'
import Admin from './Admin'
import Habits from './Habits'

const navigation=[['home','Мой день',House],['nutrition','Питание',Utensils],['workouts','Тренировки',Activity],['progress','Прогресс',Weight],['habits','Привычки',Heart],['shopping','Покупки',ShoppingCart],['profile','Профиль',UserRound]] as const
export default function Dashboard(){
  const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[selectedDate,setDate]=useState(''),[section,setSection]=useState('home'),[menu,setMenu]=useState(false),[dialog,setDialog]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const seq=useRef(0),pending=useRef(false)
  const refresh=useCallback(async()=>{const request=++seq.current;try{const next=await api<State>('/api/state'+(selectedDate?`?date=${selectedDate}`:''));if(request===seq.current){setData(next);setError('')}}catch(e){if(e instanceof ApiError&&e.status===401)location.assign('/login');if(request===seq.current)setError(errorText(e));throw e}},[selectedDate])
  useEffect(()=>{refresh().catch(()=>{});const timer=setInterval(()=>{if(!pending.current&&document.visibilityState==='visible')refresh().catch(()=>{})},20000);const focus=()=>{if(!pending.current)refresh().catch(()=>{})};window.addEventListener('focus',focus);return()=>{seq.current++;clearInterval(timer);window.removeEventListener('focus',focus)}},[refresh])
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(timer)},[notice])
  const mutate:Mutate=async(path,method,body)=>{if(pending.current)throw new Error('Дождитесь сохранения предыдущего изменения');pending.current=true;setBusy(true);setError('');try{await api(path,method,body);await refresh();setNotice('Сохранено')}catch(e){setError(errorText(e));throw e}finally{pending.current=false;setBusy(false)}}
  const execute=(path:string,method:string,body?:unknown)=>mutate(path,method,body).catch(()=>{})
  if(!data)return <div className="loading-page"><Logo/><p>{error||'Открываем твой день…'}</p>{error&&<button className="primary-button" onClick={()=>refresh().catch(()=>{})}>Повторить</button>}</div>
  const day=data.date,latest=data.weights.filter(w=>w.date<=day).at(-1),first=data.weights[0]
  const nutrition=data.meals.filter(m=>m.eaten).reduce((sum,m)=>({kcal:sum.kcal+m.snapshot.kcal*m.servings,p:sum.p+m.snapshot.p*m.servings,f:sum.f+m.snapshot.f*m.servings,c:sum.c+m.snapshot.c*m.servings}),{kcal:0,p:0,f:0,c:0})
  function navigate(next:string){setSection(next);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})}
  function changeDay(offset:number){const next=new Date(day+'T12:00:00Z');next.setUTCDate(next.getUTCDate()+offset);setDate(next.toISOString().slice(0,10))}
  return <div className="app-shell workspace">
    {menu&&<button className="menu-scrim" aria-label="Закрыть меню" onClick={()=>setMenu(false)}/>}
    <aside className={`sidebar ${menu?'is-open':''}`}><a className="brand-link" href="/"><Logo/><span className="brand-caption">ТВОЙ ЛИЧНЫЙ РИТМ</span></a><nav aria-label="Основная навигация">{navigation.map(([id,name,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>navigate(id)}><Icon size={21}/>{name}</button>)}{data.user.role==='admin'&&<button className={section==='admin'?'active':''} onClick={()=>navigate('admin')}><Settings size={21}/>Управление</button>}</nav><div className="workspace-side-note"><Heart size={24}/><p>Не идеальный день.<br/>Твой настоящий день.</p></div><button className="logout-button" onClick={()=>{api('/api/auth/logout','POST',{}).then(()=>location.assign('/')).catch(e=>setError(errorText(e)))}}><LogOut size={17}/>Выйти</button></aside>
    <main><header className="topbar"><button className="icon-button mobile-menu" aria-label="Открыть меню" onClick={()=>setMenu(true)}><Menu/></button><span className="workspace-greeting">Привет, <strong>{data.user.name}</strong></span><div className="day-control"><button className="icon-button" aria-label="Предыдущий день" onClick={()=>changeDay(-1)}><ChevronLeft size={17}/></button><input type="date" aria-label="Дата дневника" value={day} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/><button className="icon-button" aria-label="Следующий день" onClick={()=>changeDay(1)}><ChevronRight size={17}/></button><button className="text-button" onClick={()=>setDate('')}>Сегодня</button></div><button className="icon-button" aria-label="Обновить данные" onClick={()=>refresh().catch(()=>{})}><RefreshCw size={18}/></button></header>
    <div className="page-content"><div className="page-heading"><div><span className="eyebrow">ЗАБОТА О СЕБЕ КАЖДЫЙ ДЕНЬ</span><h1>{navigation.find(n=>n[0]===section)?.[1]||'Управление сервисом'}</h1></div><span className="sync-status">{busy?'Сохраняем…':'Записи в твоём аккаунте'}</span></div><ErrorMessage error={error}/>
    {section==='home'&&<><section className="hero workspace-hero"><div className="hero-content"><span className="eyebrow">МАЛЕНЬКИЕ ШАГИ · НАСТОЯЩИЙ ПРОГРЕСС</span><h2>В своём ритме.<br/>Каждый день.</h2><p>Сегодня — ещё одна возможность позаботиться о себе.</p><button className="primary-button" onClick={()=>setDialog('weight')}>Записать вес <Plus size={17}/></button></div></section><div className="overview-stats"><button className="card" onClick={()=>setDialog('weight')}><Weight/><span>Последняя запись веса<strong>{latest?`${fmt(latest.value)} кг`:'Пока нет записи'}</strong><small>{latest?latest.date:'Добавь первую запись'}</small></span></button><button className="card" onClick={()=>navigate('profile')}><Flag/><span>Твоя цель<strong>{({wellbeing:'Самочувствие',lose:'Снижение веса',gain:'Набор веса',maintain:'Поддержание'} as Record<string,string>)[data.user.goal]}</strong><small>{data.user.target?`Ориентир: ${fmt(data.user.target)} кг`:'В своём темпе'}</small></span></button><button className="card" onClick={()=>navigate('nutrition')}><Utensils/><span>Съедено за день<strong>{fmt(nutrition.kcal)} ккал</strong><small>Б {fmt(nutrition.p)} · Ж {fmt(nutrition.f)} · У {fmt(nutrition.c)}</small></span></button></div></>}
    {['home','progress','habits'].includes(section)&&<div className="journal-grid">
      {section!=='habits'&&<section className="card"><Title action={()=>setDialog('weight')} label="Записать вес">История веса</Title>{data.weights.filter(w=>w.date<=day).length?<><WeightChart values={data.weights.filter(w=>w.date<=day).slice(-30)}/>{first&&latest&&<p className="history-delta">{fmt(latest.value-first.value)} кг от первой записи · без оценок, только твой путь</p>}<div className="weight-history">{data.weights.filter(w=>w.date<=day).slice(-7).reverse().map(w=><div key={w.date}><span>{w.date}</span><strong>{fmt(w.value)} кг</strong><button className="text-button" onClick={()=>{setDate(w.date);setDialog('weight')}}>Изменить</button><button className="text-button danger" disabled={busy} onClick={()=>execute('/api/weights','DELETE',{date:w.date})}>Удалить</button></div>)}</div></>:<Empty action={()=>setDialog('weight')} label="Записать вес">Добавь первую запись. Здесь появится твоя история.</Empty>}</section>}
      {section!=='progress'&&<Habits data={data} mutate={mutate} busy={busy} full={section==='habits'}/>}    </div>}
    {section==='home'&&<div className="home-shortcuts">{[['nutrition','Питание',`${data.meals.length} записей в плане`],['workouts','Тренировки',`${data.workouts.filter(w=>w.date===day).length} занятий за день`],['shopping','Покупки',`${data.shopping.filter(s=>!s.checked).length} продуктов осталось`]].map(([id,label,text])=><button className="card" key={id} onClick={()=>navigate(id)}><span><strong>{label}</strong><small>{text}</small></span><ArrowRight size={20}/></button>)}</div>}
    {section==='nutrition'&&<Nutrition data={data} mutate={mutate} busy={busy}/>}{section==='workouts'&&<Workouts data={data} mutate={mutate} busy={busy}/>}{section==='shopping'&&<Shopping data={data} mutate={mutate} busy={busy}/>}{section==='profile'&&<Profile user={data.user} mutate={mutate} busy={busy}/>}{section==='admin'&&data.user.role==='admin'&&<Admin data={data} mutate={mutate}/>}
    <footer className="page-footer"><span>TELO365 · Твой личный ритм</span><a href="/privacy">О данных и доступе</a></footer></div></main>
    {notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
    {dialog==='weight'&&<Dialog title="Запись веса" close={()=>setDialog('')}><form className="workspace-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await mutate('/api/weights','PUT',{date:f.get('date'),value:Number(f.get('value'))});setDialog('')}catch{}}}><label>Дата<input name="date" type="date" defaultValue={day>data.today?data.today:day} max={data.today} required/></label><label>Вес, кг<input name="value" type="number" min={30} max={350} step="0.1" defaultValue={data.weights.find(w=>w.date===day)?.value} required autoFocus/></label><p className="form-note">Одна запись на дату. Повторное сохранение обновит её.</p><ErrorMessage error={error}/><button className="primary-button" disabled={busy}>Сохранить</button></form></Dialog>}

  </div>
}
function WeightChart({values}:{values:{date:string;value:number}[]}){
  const low=Math.min(...values.map(v=>v.value))-1,high=Math.max(...values.map(v=>v.value))+1,start=Date.parse(values[0].date),end=Date.parse(values.at(-1)!.date)
  const x=(date:string)=>end===start?180:45+(Date.parse(date)-start)/(end-start)*290,y=(value:number)=>145-(value-low)/(high-low)*120
  return <svg className="real-chart" viewBox="0 0 365 185" role="img" aria-label="График записей веса">{[0,1,2,3].map(i=><g key={i}><line x1="40" x2="340" y1={25+i*40} y2={25+i*40} stroke="#e9eee6"/><text x="2" y={29+i*40}>{fmt(high-(high-low)*i/3)}</text></g>)}<polyline points={values.map(v=>`${x(v.date)},${y(v.value)}`).join(' ')} fill="none" stroke="#528345" strokeWidth="2.5"/>{values.map(v=><circle key={v.date} cx={x(v.date)} cy={y(v.value)} r="4" fill="#528345" stroke="white"><title>{v.date}: {fmt(v.value)} кг</title></circle>)}<text x="45" y="175">{values[0].date}</text><text x="335" y="175" textAnchor="end">{values.length>1?values.at(-1)!.date:''}</text></svg>
}
