import { useState } from 'react'
import { Check, Plus, Utensils } from 'lucide-react'
import { fmt, type CatalogItem, type Meal, type Mutate, type State } from '../api'
import { Dialog, Empty, ErrorMessage, errorText, Title } from './ui'
import CatalogEditor from './CatalogEditor'
import NutritionPlanner from './NutritionPlanner'
export default function Nutrition({data,mutate,busy}:{data:State;mutate:Mutate;busy:boolean}){
  const [query,setQuery]=useState(''),[kind,setKind]=useState('recipe'),[editor,setEditor]=useState(''),[item,setItem]=useState<CatalogItem|undefined>(),[adding,setAdding]=useState<CatalogItem|null>(null),[editMeal,setEditMeal]=useState<Meal|null>(null),[error,setError]=useState('')
  const items=data.catalog.filter(i=>i.kind===kind&&i.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()))
  const totals=data.meals.filter(m=>m.eaten).reduce((s,m)=>{for(const k of ['kcal','p','f','c'] as const)s[k]+=m.snapshot[k]*m.servings;return s},{kcal:0,p:0,f:0,c:0})
  const perform=async(path:string,method:string,body?:unknown)=>{setError('');try{await mutate(path,method,body)}catch(e){setError(errorText(e))}}
  return <div className="nutrition-layout"><NutritionPlanner data={data} mutate={mutate} busy={busy}/><section className="card"><Title>Питание за {data.date}</Title><div className="real-macros">{[['kcal','Ккал'],['p','Белки'],['f','Жиры'],['c','Углеводы']].map(([key,label])=><div key={key}><small>{label}</small><strong>{fmt(totals[key as 'kcal'])}{key==='kcal'?'':' г'}</strong></div>)}</div>{data.user.calories&&<p className="form-note">Личный ориентир: {fmt(data.user.calories)} ккал. Учитываются только отмеченные приёмы пищи.</p>}<ErrorMessage error={error}/>{!data.meals.length?<Empty>Выбери продукт или рецепт из каталога и добавь его в свой день.</Empty>:data.meals.map(m=><article className="journal-meal" key={m.id}><img src={`/images/${m.snapshot.image}.jpg`} alt=""/><div><span className="eyebrow">{m.slot} · {fmt(m.servings)} порц.</span><h3>{m.snapshot.name}</h3><p>{fmt(m.snapshot.kcal*m.servings)} ккал · Б {fmt(m.snapshot.p*m.servings)} · Ж {fmt(m.snapshot.f*m.servings)} · У {fmt(m.snapshot.c*m.servings)}</p>{m.snapshot.sample&&<small className="sample-note">Справочный пример</small>}<div className="row-actions"><button className={m.eaten?'soft-button':'text-button'} disabled={busy||data.date>data.today} onClick={()=>perform('/api/meals','PUT',{id:m.id,date:m.date,slot:m.slot,servings:m.servings,eaten:!m.eaten})}>{m.eaten?<><Check size={13}/>Съедено</>:'Отметить съеденным'}</button><button className="text-button" onClick={()=>setEditMeal(m)}>Порция / дата</button><button className="text-button danger" disabled={busy} onClick={()=>perform(`/api/meals/${m.id}`,'DELETE',{})}>Удалить</button></div></div></article>)}</section>
    <section className="card"><Title>Каталог</Title><div className="tabs"><button className={kind==='recipe'?'selected':''} onClick={()=>setKind('recipe')}>Рецепты</button><button className={kind==='food'?'selected':''} onClick={()=>setKind('food')}>Продукты</button></div><input className="catalog-search" aria-label="Найти в каталоге" placeholder="Найти продукт или рецепт" value={query} onChange={e=>setQuery(e.target.value)}/><div className="row-actions"><button className="soft-button" onClick={()=>{setItem(undefined);setEditor('food')}}><Plus size={14}/>Свой продукт</button><button className="soft-button" onClick={()=>{setItem(undefined);setEditor('recipe')}}><Plus size={14}/>Свой рецепт</button></div><p className="form-note">Начальные продукты — учебные примеры. Для точного дневника добавь данные с упаковки. Порция продукта равна 100 г.</p><div className="catalog-list">{items.map(i=><article className="catalog-item" key={i.id}><span className="round-icon green"><Utensils size={19}/></span><div><h3>{i.name}</h3><p>{fmt(i.nutrition?.kcal??i.kcal??0)} ккал / {i.kind==='food'?'100 г':'порцию'}</p>{i.source&&<small>{i.source}</small>}<div className="row-actions"><button className="text-button" onClick={()=>setAdding(i)}>В мой день <Plus size={13}/></button>{i.owner===data.user.id&&<button className="text-button" onClick={()=>{setItem(i);setEditor(i.kind)}}>Изменить</button>}</div></div></article>)}</div>{!items.length&&<Empty>Ничего не найдено. Можно добавить свой продукт.</Empty>}</section>
    {editor&&<Dialog title={editor==='food'?'Свой продукт':'Свой рецепт'} close={()=>setEditor('')}><CatalogEditor kind={editor} item={item} catalog={data.catalog} mutate={mutate} done={()=>setEditor('')}/></Dialog>}
    {(adding||editMeal)&&<Dialog title={adding?.name||editMeal!.snapshot.name} close={()=>{setAdding(null);setEditMeal(null);setError('')}}>{adding?.instructions&&<p className="dialog-intro">{adding.instructions}</p>}{adding?.nutrition&&<ul className="recipe-ingredients">{adding.nutrition.ingredients.map((i,n)=><li key={n}>{i.name} · {fmt(i.grams)} г</li>)}</ul>}<MealForm item={adding} meal={editMeal} day={data.date} today={data.today} mutate={mutate} done={()=>{setAdding(null);setEditMeal(null)}}/></Dialog>}
  </div>
}
function MealForm({item,meal,day,today,mutate,done}:{item:CatalogItem|null;meal:Meal|null;day:string;today:string;mutate:Mutate;done:()=>void}){
  const [id]=useState(meal?.id||crypto.randomUUID()),[error,setError]=useState(''),[busy,setBusy]=useState(false),[portions,setPortions]=useState(meal?.servings||1)
  const kcal=meal?.snapshot.kcal??item?.nutrition?.kcal??item?.kcal??0
  return <form className="workspace-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await mutate('/api/meals','PUT',{id,date:f.get('date'),catalogId:item?.id,slot:f.get('slot'),servings:portions,eaten:f.get('eaten')==='on'});done()}catch(e){setError(errorText(e))}finally{setBusy(false)}}}><label>Дата<input name="date" type="date" defaultValue={meal?.date||day} required/></label><label>Приём пищи<select name="slot" defaultValue={meal?.slot||'Завтрак'}>{['Завтрак','Обед','Ужин','Перекус'].map(s=><option key={s}>{s}</option>)}</select></label><label>{item?.kind==='food'?'Порции по 100 г':'Количество порций'}<input type="number" min="0.01" max="100" step="0.01" value={portions} onChange={e=>setPortions(Number(e.target.value))} required/></label><p className="portion-total">{fmt(kcal*portions)} ккал{item?.kind==='food'?` · ${fmt(portions*100)} г`:''}</p><label className="consent"><input name="eaten" type="checkbox" defaultChecked={meal?.eaten||false} disabled={day>today}/>Уже съедено</label><ErrorMessage error={error}/><button className="primary-button" disabled={busy}>Сохранить приём пищи</button></form>
}
