import { useMemo, useState } from 'react'
import { CalendarDays, Check, ChefHat, Sparkles } from 'lucide-react'
import { fmt, type CatalogItem, type Mutate, type NutritionProfile, type State } from '../api'
import { ErrorMessage, errorText } from './ui'
import '../nutrition-planner.css'

const slots=['Завтрак','Обед','Ужин'] as const
type PlannedMeal={date:string;slot:string;recipe:CatalogItem}
const plusDays=(date:string,days:number)=>{const value=new Date(`${date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10)}
const shortDate=(date:string)=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`)).replace('.','')

export default function NutritionPlanner({data,mutate,busy}:{data:State;mutate:Mutate;busy:boolean}) {
  const [profile,setProfile]=useState<NutritionProfile>(data.nutritionProfile||{style:'mixed',cooking:'quick',budget:'balanced',exclusions:''})
  const [shown,setShown]=useState(!!data.nutritionProfile),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  const recipes=useMemo(()=>data.catalog.filter(item=>item.kind==='recipe'&&item.nutrition),[data.catalog])
  const excluded=profile.exclusions.toLocaleLowerCase('ru').split(',').map(value=>value.trim()).filter(Boolean)
  const available=recipes.filter(recipe=>!excluded.some(word=>recipe.nutrition?.ingredients.some(ingredient=>ingredient.name.toLocaleLowerCase('ru').includes(word))))
  const source=available.length?available:recipes
  const plan=useMemo<PlannedMeal[]>(()=>Array.from({length:7},(_,day)=>slots.map((slot,index)=>({date:plusDays(data.date,day),slot,recipe:source[(day*2+index)%Math.max(1,source.length)]}))).flat(),[data.date,source])
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await mutate('/api/nutrition/profile','PUT',profile);setShown(true)}catch(reason){setError(errorText(reason))}finally{setSaving(false)}}
  async function addWeek(){setSaving(true);setError('');try{for(const meal of plan)await mutate('/api/meals','PUT',{id:crypto.randomUUID(),date:meal.date,slot:meal.slot,catalogId:meal.recipe.id,servings:1,eaten:false})}catch(reason){setError(errorText(reason))}finally{setSaving(false)}}
  return <section className="card nutrition-planner"><div className="planner-heading"><span className="round-icon green"><Sparkles/></span><div><h2>Подобрать рацион</h2><p>План на неделю из рецептов каталога, под твой режим.</p></div></div>{!shown?<form className="workspace-form planner-form" onSubmit={save}><label>Как тебе удобнее?<select value={profile.style} onChange={e=>setProfile({...profile,style:e.target.value as NutritionProfile['style']})}><option value="home">Готовить дома</option><option value="mixed">Готовить и иногда заказывать</option><option value="ready">Больше готовой еды</option></select></label><div className="form-grid"><label>Время на готовку<select value={profile.cooking} onChange={e=>setProfile({...profile,cooking:e.target.value as NutritionProfile['cooking']})}><option value="quick">До 20 минут</option><option value="normal">До 45 минут</option><option value="free">Время есть</option></select></label><label>Бюджет<select value={profile.budget} onChange={e=>setProfile({...profile,budget:e.target.value as NutritionProfile['budget']})}><option value="economy">Экономно</option><option value="balanced">Умеренно</option><option value="free">Без ограничения</option></select></label></div><label>Что исключить?<input value={profile.exclusions} onChange={e=>setProfile({...profile,exclusions:e.target.value})} maxLength={300} placeholder="Например: молоко, курица, орехи"/><small>Здесь можно исключить продукты из подборки. Медицинские ограничения нужно согласовать со специалистом.</small></label><ErrorMessage error={error}/><button className="primary-button" disabled={saving||busy}><ChefHat size={17}/>Собрать план</button></form>:<><div className="planner-summary"><span><CalendarDays size={16}/>7 дней · {profile.style==='home'?'домашняя еда':profile.style==='mixed'?'гибкий режим':'готовые решения'}</span><button className="text-button" onClick={()=>setShown(false)}>Изменить ответы</button></div><div className="planner-days">{Array.from({length:7},(_,day)=>{const date=plusDays(data.date,day),items=plan.filter(item=>item.date===date),total=items.reduce((sum,item)=>sum+(item.recipe.nutrition?.kcal||0),0);return <article key={date}><small>{day===0?'Сегодня':shortDate(date)}</small>{items.map(item=><div key={item.slot}><span>{item.slot}</span><strong>{item.recipe.name}</strong><em>{fmt(item.recipe.nutrition?.kcal||0)} ккал</em></div>)}<b className="planner-day-total">Итого: {fmt(total)} ккал</b></article>})}</div>{!available.length&&excluded.length>0&&<p className="form-note">Подходящих рецептов в каталоге пока мало: проверь варианты и замени их при необходимости.</p>}<ErrorMessage error={error}/><button className="primary-button" disabled={saving||busy||!source.length} onClick={addWeek}><Check size={17}/>Использовать этот рацион</button><p className="form-note">Приёмы добавятся как запланированные. Затем в «Покупках» можно собрать единый список ингредиентов.</p></>}</section>
}
