import { useState } from 'react'
import { api, download, type User, type Mutate } from '../api'
import { Dialog, ErrorMessage, errorText, Title } from './ui'
export default function Profile({user,mutate,busy}:{user:User;mutate:Mutate;busy:boolean}){
  const [error,setError]=useState(''),[action,setAction]=useState(''),[code,setCode]=useState(''),[working,setWorking]=useState(false)
  return <div className="profile-layout"><section className="card"><Title>Твой профиль</Title><form className="workspace-form" onSubmit={async e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{await mutate('/api/profile','PUT',{name:f.get('name'),goal:f.get('goal'),target:f.get('target')?Number(f.get('target')):null,calories:f.get('calories')?Number(f.get('calories')):null,timezone:f.get('timezone')})}catch(e){setError(errorText(e))}}}><label>Имя<input name="name" defaultValue={user.name} required maxLength={60}/></label><label>Email<input type="email" value={user.email} readOnly/><small>Используется для входа. Подтверждение почты пока не подключено.</small></label><label>Цель<select name="goal" defaultValue={user.goal}><option value="wellbeing">Лучше себя чувствовать</option><option value="lose">Снизить вес</option><option value="gain">Набрать вес</option><option value="maintain">Поддерживать форму</option></select></label><label>Целевой вес, кг · необязательно<input type="number" name="target" min={30} max={350} step="0.1" defaultValue={user.target??''}/></label><label>Личный ориентир калорий · необязательно<input name="calories" type="number" min={500} max={8000} defaultValue={user.calories??''}/><small>Заполняется самостоятельно. Сервис не назначает норму питания.</small></label><label>Часовой пояс<input name="timezone" defaultValue={user.timezone} list="timezones" required/><datalist id="timezones">{['Europe/Moscow','Europe/Kaliningrad','Europe/Samara','Asia/Yekaterinburg','Asia/Omsk','Asia/Krasnoyarsk','Asia/Irkutsk','Asia/Yakutsk','Asia/Vladivostok','Asia/Kamchatka','UTC'].map(t=><option key={t}>{t}</option>)}</datalist></label><ErrorMessage error={error}/><button className="primary-button" disabled={busy}>Сохранить профиль</button></form></section><section className="card"><Title>Доступ и данные</Title><div className="account-actions"><button className="soft-button" onClick={()=>setAction('password')}>Изменить пароль</button><button className="soft-button" onClick={()=>setAction('recovery-code')}>Новый резервный код</button><button className="soft-button" onClick={()=>api('/api/export').then(r=>download('telo365-data.json',JSON.stringify(r,null,2),'application/json')).catch(e=>setError(errorText(e)))}>Скачать мои данные</button><button className="danger-button" onClick={()=>setAction('delete')}>Удалить аккаунт</button></div><p className="form-note">Записи доступны на всех устройствах после входа. Резервный код позволяет восстановить доступ без писем.</p></section>
  {action&&<Dialog title={action==='delete'?'Удаление аккаунта':action==='password'?'Изменить пароль':'Новый резервный код'} close={()=>{if(!working){setAction('');setError('')}}}><form className="workspace-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setWorking(true);setError('');try{const r=await api<{recoveryCode?:string}>(`/api/auth/${action}`,'POST',{password:f.get('password'),newPassword:f.get('newPassword')});if(action==='delete')location.assign('/');else{setCode(r.recoveryCode||'');setAction('')}}catch(e){setError(errorText(e))}finally{setWorking(false)}}}>{action==='delete'&&<p>Все записи и активные сеансы будут удалены. Это действие нельзя отменить. При необходимости сначала скачай свои данные.</p>}<label>Текущий пароль<input type="password" name="password" minLength={12} maxLength={128} required autoComplete="current-password"/></label>{action==='password'&&<label>Новый пароль<input type="password" name="newPassword" minLength={12} maxLength={128} required autoComplete="new-password"/></label>}<ErrorMessage error={error}/><button className={action==='delete'?'danger-button':'primary-button'} disabled={working}>{action==='delete'?'Удалить навсегда':'Сохранить'}</button></form></Dialog>}
  {code&&<Dialog title="Сохрани новый код" close={()=>setCode('')}><p>Предыдущий код больше не действует.</p><code className="recovery-code">{code}</code><button className="soft-button" onClick={()=>download('telo365-recovery.txt',code)}>Скачать код</button><button className="primary-button" onClick={()=>setCode('')}>Я сохранил код</button></Dialog>}
  </div>
}
