import { useState } from 'react'
import { Check, ShoppingBasket } from 'lucide-react'
import { fmt, type State, type Mutate } from '../api'
import { Empty, ErrorMessage, errorText, Title } from './ui'
import StoreLinks, { perekrestokSearch } from './StoreLinks'
export default function Shopping({data,mutate,busy}:{data:State;mutate:Mutate;busy:boolean}){
  const [error,setError]=useState(''),[from,setFrom]=useState(data.date),[to,setTo]=useState(()=>{const d=new Date(data.date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+6);return d.toISOString().slice(0,10)}),[manualId,setManualId]=useState(()=>crypto.randomUUID())
  const perform=async(path:string,method:string,body:unknown)=>{setError('');try{await mutate(path,method,body)}catch(e){setError(errorText(e));throw e}}
  return <div className="journal-grid"><section className="card"><Title>Список покупок</Title><ErrorMessage error={error}/>{data.shopping.length?data.shopping.map(s=><div className={`shopping-row ${s.checked?'is-checked':''}`} key={s.id}><button disabled={busy} aria-pressed={!!s.checked} aria-label={`${s.name}: ${s.checked?'куплено':'купить'}`} onClick={()=>perform('/api/shopping','PUT',{...s,checked:!s.checked}).catch(()=>{})}><span className={`habit-check ${s.checked?'checked':''}`}>{!!s.checked&&<Check size={13}/>}</span><span><strong>{s.name}</strong><small>{s.generated?'Из плана питания':'Добавлено вручную'}</small></span></button><span>{fmt(s.amount)} {s.unit}</span><a className="text-button" target="_blank" rel="noreferrer" href={perekrestokSearch(s.name)}>Цена ↗</a><button className="text-button danger" disabled={busy} aria-label={`Удалить ${s.name}`} onClick={()=>perform(`/api/shopping/${s.id}`,'DELETE',{}).catch(()=>{})}>×</button></div>):<Empty>Добавь продукты вручную или собери список из плана питания.</Empty>}<p className="form-note">Куплено {data.shopping.filter(s=>s.checked).length} из {data.shopping.length}. Цены магазинов пока не подключены.</p><StoreLinks items={data.shopping}/></section><section className="card"><Title>Собрать из плана</Title><p className="dialog-intro">Ингредиенты всех блюд за выбранные дни объединятся по названию. Ручные позиции сохранятся. При изменении количества отметку покупки нужно будет поставить заново.</p><form className="workspace-form" onSubmit={e=>{e.preventDefault();perform('/api/shopping/generate','POST',{from,to}).catch(()=>{})}}><div className="form-grid"><label>С даты<input type="date" value={from} onChange={e=>setFrom(e.target.value)} required/></label><label>По дату<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)} required/></label></div><button className="primary-button" disabled={busy}><ShoppingBasket size={17}/>Обновить из плана</button></form><h3 className="subheading">Добавить вручную</h3><form className="workspace-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await perform('/api/shopping','PUT',{id:manualId,name:f.get('name'),amount:Number(f.get('amount')),unit:f.get('unit'),checked:false});form.reset();setManualId(crypto.randomUUID())}catch{}}}><label>Продукт<input name="name" maxLength={120} required/></label><div className="form-grid"><label>Количество<input type="number" name="amount" min="0.01" max="1000000" step="0.01" defaultValue={1} required/></label><label>Единица<select name="unit"><option>шт.</option><option>г</option><option>кг</option><option>мл</option><option>л</option><option>уп.</option></select></label></div><button className="soft-button" disabled={busy}>Добавить продукт</button></form></section></div>
}
