import { useState } from 'react'
import { Activity, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Dumbbell, Play, Plus } from 'lucide-react'
import { type CatalogItem, type ExerciseLog, type Mutate, type State, type Workout } from '../api'
import { Dialog, Empty, ErrorMessage, errorText, Title } from './ui'
export default function Workouts({data,mutate,busy}:{data:State;mutate:Mutate;busy:boolean}){
  const [editing,setEditing]=useState<Workout|null>(null),[error,setError]=useState(''),[creating,setCreating]=useState(false)
  const programs=data.catalog.filter(i=>i.kind==='program'),logs=data.workouts.filter(w=>w.date===data.date)
  const start=async(program:CatalogItem)=>{setCreating(true);setError('');try{await mutate('/api/workouts','PUT',{id:crypto.randomUUID(),programId:program.id,date:data.date,finished:false})}catch(reason){setError(errorText(reason))}finally{setCreating(false)}}
  return <><WorkoutOverview data={data} logs={logs} programs={programs} busy={busy||creating} start={start} open={workout=>setEditing(workout)}/><div className="journal-grid workout-journal"><section className="card"><Title>Тренировки за день</Title><ErrorMessage error={error}/>{logs.length?logs.map(w=><article className="workout-log" key={w.id}><span className="round-icon green">{w.finished?<Check/>:<Activity/>}</span><div><h3>{w.data.name}</h3><p>{w.finished?'Завершена':'В процессе'} · {w.data.exercises.reduce((n,e)=>n+e.sets.filter(s=>s.done).length,0)} подходов выполнено</p><div className="row-actions"><button className="soft-button" onClick={()=>setEditing(w)}>{w.finished?'Посмотреть записи':'Продолжить'}</button><button className="text-button danger" disabled={busy} onClick={()=>mutate(`/api/workouts/${w.id}`,'DELETE',{}).catch(e=>setError(errorText(e)))}>Удалить</button></div></div></article>):<Empty>Выбери программу и начни своё занятие. Записи подходов сохраняются в аккаунте.</Empty>}<h3 className="subheading">Предыдущие занятия</h3>{data.workouts.filter(w=>w.date!==data.date).slice(0,12).map(w=><button className="history-workout" key={w.id} onClick={()=>setEditing(w)}><span>{w.date}</span><strong>{w.data.name}</strong><small>{w.finished?'Завершена':'Не завершена'}</small></button>)}</section><section className="card workout-programs"><Title>Программы</Title><p className="form-note">Выбери программу под свой ритм. Нагрузку и количество подходов можно менять в любой момент.</p><div className="program-grid">{programs.map(p=><article className="program-card" key={p.id}><div className="program-cover"><Activity size={25}/><h3>{p.name}</h3><span><Clock3 size={14}/>{p.minutes} минут</span></div><p>{p.description}</p><ul>{p.exercises?.map((e,i)=><li key={i}>{data.catalog.find(c=>c.id===e.exerciseId)?.name} · {e.sets} × {e.reps}</li>)}</ul><button className="primary-button" disabled={busy||creating} onClick={()=>start(p)}>Начать тренировку <Plus size={16}/></button></article>)}</div><h3 className="subheading">Упражнения</h3>{data.catalog.filter(i=>i.kind==='exercise').map(e=><details className="exercise-detail" key={e.id}><summary>{e.name}</summary><p>{e.muscle} · {e.description}</p></details>)}</section>{editing&&<Dialog title={editing.data.name} close={()=>setEditing(null)}><WorkoutForm workout={editing} history={data.workouts} mutate={mutate} done={()=>setEditing(null)}/></Dialog>}</div></>
}

function WorkoutOverview({data,logs,programs,busy,start,open}:{data:State;logs:Workout[];programs:CatalogItem[];busy:boolean;start:(program:CatalogItem)=>Promise<void>;open:(workout:Workout)=>void}) {
  const active=logs.find(workout=>!workout.finished),finished=logs.find(workout=>workout.finished),current=active||finished
  const total=current?.data.exercises.reduce((sum,exercise)=>sum+exercise.sets.length,0)||0
  const done=current?.data.exercises.reduce((sum,exercise)=>sum+exercise.sets.filter(set=>set.done).length,0)||0
  const quick=programs.find(program=>program.id==='quick-start')||programs[0]
  const dates=[0,2,4].map(offset=>{const value=new Date(`${data.date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+offset);return value.toISOString().slice(0,10)})
  const suggestions=[programs.find(program=>program.id==='upper-body'),programs.find(program=>program.id==='lower-body'),programs.find(program=>program.id==='full-body')].filter(Boolean) as CatalogItem[]
  return <section className="workout-overview"><article className="card workout-today"><div><span className="eyebrow">ТРЕНИРОВКА НА СЕГОДНЯ</span><h2>{active?'В процессе':finished?'Занятие завершено':'Время для движения'}</h2><p>{active?`${done} из ${total} подходов выполнено`:finished?`${finished.data.name} сохранена в истории.`:'Выбери программу или начни с короткого занятия.'}</p></div><span className={`round-icon ${finished?'green':'purple'}`}>{finished?<Check/>:<Dumbbell/>}</span>{current&&<><div className="workout-today-progress"><span>{current.data.name}</span><b>{total?Math.round(done/total*100):0}%</b></div><i><b style={{width:`${total?done/total*100:0}%`}}/></i></>}{active?<button className="primary-button" onClick={()=>open(active)}><Play size={16}/>Продолжить</button>:quick&&<button className="primary-button" disabled={busy} onClick={()=>start(quick)}><Play size={16}/>{data.date>data.today?'Запланировать':'Начать тренировку'}</button>}</article><article className="card workout-week"><div className="workout-week-head"><div><span className="eyebrow">ТВОЙ РИТМ</span><h2>План на неделю</h2></div><CalendarDays size={20}/></div><div className="workout-week-list">{dates.map((date,index)=>{const planned=suggestions[index],complete=data.workouts.some(workout=>workout.date===date&&workout.finished);return <div key={date}><span>{index===0?'Сегодня':new Intl.DateTimeFormat('ru-RU',{weekday:'short',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`))}</span><strong>{planned?.name||'Своя тренировка'}</strong>{complete?<Check size={15}/>:<i>{planned?.minutes||20} мин</i>}</div>})}</div></article></section>
}

function WorkoutForm({workout,history,mutate,done}:{workout:Workout;history:Workout[];mutate:Mutate;done:()=>void}) {
  const [exercises,setExercises]=useState<ExerciseLog[]>(structuredClone(workout.data.exercises))
  const [active,setActive]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const exercise=exercises[active],total=exercises.reduce((sum,item)=>sum+item.sets.length,0),doneSets=exercises.reduce((sum,item)=>sum+item.sets.filter(set=>set.done).length,0),allDone=total>0&&doneSets===total
  const previous=history.filter(item=>item.id!==workout.id&&item.finished&&item.data.programId===workout.data.programId).sort((a,b)=>b.date.localeCompare(a.date)).map(item=>item.data.exercises.find(value=>value.name===exercise.name)).find(Boolean)
  const previousSet=previous?.sets.find(set=>set.done)||previous?.sets[0]
  const started=workout.data.startedAt?new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(workout.data.startedAt)):null
  function change(setIndex:number,key:string,value:number|boolean){setExercises(rows=>rows.map((item,index)=>index===active?{...item,sets:item.sets.map((set,current)=>current===setIndex?{...set,[key]:value}:set)}:item))}
  function addSet(){setExercises(rows=>rows.map((item,index)=>index===active?{...item,sets:[...item.sets,{reps:exercise.sets.at(-1)?.reps||12,weight:exercise.sets.at(-1)?.weight||0,done:false}]}:item))}
  return <form className="workspace-form workout-live-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');const values=new FormData(event.currentTarget);try{await mutate('/api/workouts','PUT',{id:workout.id,date:values.get('date'),exercises,finished:values.get('finished')==='on'});done()}catch(reason){setError(errorText(reason))}finally{setBusy(false)}}}><div className="workout-live-top"><div><span>Тренировка в процессе</span><strong>{workout.data.name}</strong></div>{started&&<time>{started}</time>}</div><label className="workout-live-date">Дата<input name="date" type="date" defaultValue={workout.date} required/></label><section className="workout-live-exercise"><div className="workout-live-exercise-head"><span>Упражнение {active+1} из {exercises.length}</span><h3>{exercise.name}</h3></div>{previousSet&&<div className="workout-previous"><span>Предыдущий результат</span><strong>{previousSet.weight?`${previousSet.weight} кг ? ${previousSet.reps}`:`${previousSet.reps} ${exercise.unit==='seconds'?'секунд':'повторы'}`}</strong></div>}<div className="workout-set-table"><div className="workout-set-head"><span>Подход</span><span>Вес</span><span>{exercise.unit==='seconds'?'секунд':'повторы'}</span><span>Готово</span></div>{exercise.sets.map((set,index)=><div className={`workout-live-set ${set.done?'is-done':''}`} key={index}><b>{index+1}</b><input aria-label={`Вес ${index+1}`} type="number" min={0} max={500} step="0.5" value={set.weight} onChange={event=>change(index,'weight',Number(event.target.value))}/><input aria-label={`повторы ${index+1}`} type="number" min={1} max={3600} value={set.reps} onChange={event=>change(index,'reps',Number(event.target.value))}/><button type="button" className="workout-set-toggle" aria-label={`Отметить подход ${index+1}`} aria-pressed={set.done} onClick={()=>change(index,'done',!set.done)}>{set.done?<Check size={15}/>:null}</button></div>)}</div><button type="button" className="text-button workout-add-set" disabled={exercise.sets.length>=20} onClick={addSet}><Plus size={15}/>Добавить подход</button></section><div className="workout-live-navigation"><button type="button" className="soft-button" disabled={active===0} onClick={()=>setActive(value=>value-1)}><ChevronLeft size={15}/>Назад</button>{active<exercises.length-1?<button type="button" className="primary-button" onClick={()=>setActive(value=>value+1)}>Следующее упражнение<ChevronRight size={15}/></button>:<span>Последнее упражнение</span>}</div><label className="consent"><input name="finished" type="checkbox" defaultChecked={workout.finished} disabled={!allDone}/>Завершить тренировку</label>{!allDone&&<small>Отметь все подходы, чтобы завершить занятие. Промежуточные результаты можно сохранить.</small>}<ErrorMessage error={error}/><button className="primary-button" disabled={busy}>Сохранить тренировку</button></form>
}
