import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import { Activity, ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, Dumbbell, Play, Repeat2, ShieldCheck, Video } from 'lucide-react'
import { type CatalogItem, type ExerciseLog, type ExerciseMedia, type Mutate, type State, type TrainingDay, type TrainingPlan, type Workout } from '../api'
import { getExercise3DAsset, getExerciseTechnique, getMixamoAirSquatTestAsset, getSquatTechniqueVideo, type TrainerAvatar } from '../exercise3d'
import { Dialog, Empty, ErrorMessage, errorText, Title } from './ui'
import WorkoutHero from './WorkoutHero'
import TechniqueVideoViewer from './TechniqueVideoViewer'

const Exercise3DViewer=lazy(()=>import('./Exercise3DViewer'))

const words={
  today:'Тренировка на сегодня',week:'Твой план на неделю',workout:'Сегодняшняя тренировка',todayLabel:'Сегодня',todayRecovery:'Сегодня — восстановление',start:'Начать тренировку',continue:'Продолжить',technique:'Техника',replace:'Заменить упражнение',other:'Другие программы',recovery:'Восстановление',planned:'Запланировано',progress:'Прогресс сохраняется автоматически',
  recoveryTitle:'День восстановления',recoveryDescription:'Сегодня достаточно мягкого движения в своём ритме.',recoveryWalk:'Прогулка 20–30 минут',recoveryMobility:'Лёгкая мобилизация 5–10 минут',recoveryNoLoad:'Лёгкая активность без тяжёлой нагрузки',openRecovery:'Открыть восстановление',
  noPlan:'Персональный план появится после завершения стартовой анкеты.',otherDescription:'Дополнительные варианты для самостоятельного занятия.',showAll:'Показать все программы',hideAll:'Скрыть программы',noPrograms:'Подходящих дополнительных программ сейчас нет.',techniquePlaceholder:'Видео техники появится здесь.'
}
const noMedia:ExerciseMedia={shortVideoUrl:null,posterUrl:null,duration:null,angle:null,trainerName:null}
const trainerAvatarStorageKey='telo365.technique-trainer-avatar'
const isLocalMixamoPreview=()=>typeof window!=='undefined'&&['localhost','127.0.0.1'].includes(window.location.hostname)&&new URLSearchParams(window.location.search).get('mixamoSquatPreview')==='1'
const initialTrainerAvatar=():TrainerAvatar=>{
  if(typeof window==='undefined')return 'female'
  const saved=window.localStorage.getItem(trainerAvatarStorageKey)
  return saved==='male'||saved==='female'?saved:'female'
}
const dayName=(date:string)=>new Intl.DateTimeFormat('ru-RU',{weekday:'short',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`)).replace('.','')
const intensityLabel=(value:string)=>({light:'лёгкая',moderate:'умеренная',hard:'высокая'}[value]||value)
const equipmentLabel=(items:string[])=>(items||[]).map(item=>({dumbbells:'гантели',adjustable_dumbbells:'разборные гантели',bands:'резинки',bench:'скамья',pullup_bar:'турник'}[item]||item)).join(' · ')
const rpeLabel=(value?:number)=>value&&value<=4?'Лёгкая нагрузка':value&&value<=6?'Умеренная нагрузка':'Высокая нагрузка'
const rpeHint=(value?:number)=>value&&value<=4?'Оставь примерно 5–6 повторений в запасе.':value&&value<=6?'Оставь примерно 3–4 повторения в запасе.':'Оставь примерно 1–2 повторения в запасе.'
const clock=(seconds:number)=>{const rounded=Math.max(0,Math.ceil(seconds));return `${Math.floor(rounded/60).toString().padStart(2,'0')}:${(rounded%60).toString().padStart(2,'0')}`}

type TechniqueItem={exerciseId:string;name:string;media:ExerciseMedia}
type WorkoutCompletion={name:string;elapsedMinutes:number;completedExercises:number;totalExercises:number;completedSets:number;totalSets:number;totalVolumeKg:number;feedbackLabel:string;painOrDiscomfort:boolean}
// A session may have been saved before the catalog metadata correction. Keep
// its history intact while preventing the old label from misdescribing Air Squat.
const techniqueExerciseName=(item:{exerciseId:string;name:string})=>item.exerciseId==='squat'?'Приседания':item.name

export default function Workouts({data,mutate,busy,onGoHome}:{data:State;mutate:Mutate;busy:boolean;onGoHome?:()=>void}){
  const [editing,setEditing]=useState<Workout|null>(null),[error,setError]=useState(''),[creating,setCreating]=useState(false),[overrides,setOverrides]=useState<Record<string,string>>({}),[technique,setTechnique]=useState<TechniqueItem|null>(null),[showAllPrograms,setShowAllPrograms]=useState(false),[completion,setCompletion]=useState<WorkoutCompletion|null>(null)
  const [trainerAvatar,setTrainerAvatar]=useState<TrainerAvatar>(initialTrainerAvatar)
  const mixamoTechniquePreviewEnabled=isLocalMixamoPreview()
  useEffect(()=>{try{window.localStorage.setItem(trainerAvatarStorageKey,trainerAvatar)}catch{/* Storage is optional for the technique viewer. */}},[trainerAvatar])
  const plan=data.trainingPlan as TrainingPlan|undefined|null
  const week=plan?.currentWeek
  const todayDay=week?.days.find(day=>day.date===data.date)
  const logs=data.workouts.filter(workout=>workout.date===data.date)
  const active=logs.find(workout=>!workout.finished),finished=logs.find(workout=>workout.finished)
  const activeMatchesPlan=!!active&&!!plan&&active.data.planId===plan.id&&active.data.trainingDayId===todayDay?.id
  const activeOutsidePlan=!!active&&!!todayDay&&!activeMatchesPlan
  const isRecoveryDay=!!todayDay?.recoveryDay
  const isRecovery=isRecoveryDay&&!active&&!finished
  const exerciseById=new Map(data.catalog.filter(item=>item.kind==='exercise').map(item=>[item.id,item]))
  const blockedAreas=new Set(plan?.safety.blockedExerciseAreas||[]),planEquipment=new Set(Array.isArray(plan?.source.equipment)?plan.source.equipment:[]),hasGym=Array.isArray(plan?.source.locations)&&plan.source.locations.includes('gym')&&(planEquipment.has('standard_gym')||planEquipment.has('machines')||planEquipment.has('barbell')),genericPrograms=data.catalog.filter(item=>item.kind==='program').filter(program=>plan?.status!=='needs_review'&&!(plan?.safety.intensityLimited&&program.intensity==='hard')&&(program.exercises||[]).every(entry=>{const exercise=exerciseById.get(entry.exerciseId);return !!exercise&&(hasGym||(exercise.equipment||[]).every(item=>planEquipment.has(item)||(item==='dumbbells'&&planEquipment.has('adjustable_dumbbells'))))&&!exercise.contraindications?.some(area=>blockedAreas.has(area))}))
  const visiblePrograms=showAllPrograms?genericPrograms:genericPrograms.slice(0,4)
  useEffect(()=>setCompletion(null),[data.date])
  const startPersonal=async()=>{if(!plan||!todayDay)return;setCreating(true);setError('');setCompletion(null);try{await mutate('/api/workouts','PUT',{id:crypto.randomUUID(),planId:plan.id,trainingDayId:todayDay.id,date:data.date,exerciseOverrides:overrides,finished:false})}catch(reason){setError(errorText(reason))}finally{setCreating(false)}}
  const startGeneric=async(program:CatalogItem)=>{setCreating(true);setError('');setCompletion(null);try{await mutate('/api/workouts','PUT',{id:crypto.randomUUID(),programId:program.id,date:data.date,finished:false})}catch(reason){setError(errorText(reason))}finally{setCreating(false)}}
  const cycleVariant=(item:TrainingDay['exercises'][number])=>{const choices=[item.exerciseId,...item.variants],current=overrides[item.exerciseId]||item.exerciseId,next=choices[(choices.indexOf(current)+1)%choices.length];setOverrides(value=>({...value,[item.exerciseId]:next}))}
  const sessionProps=active?{workout:active,mutate,catalogExercises:exerciseById,onTechnique:setTechnique,outsidePlan:activeOutsidePlan,onCompleted:(value:WorkoutCompletion)=>{setCompletion(value);setEditing(null)}}:null
  const todayTitle=active?(activeOutsidePlan?'Активная тренировка':words.workout):isRecoveryDay?words.todayRecovery:words.workout
  return <>
    <WorkoutHero hasActiveWorkout={!!active}/>
    <section className="workout-overview personal-workout-overview">
      <TodayCard plan={plan} day={todayDay} active={active} finished={finished} outsidePlan={activeOutsidePlan} busy={busy||creating} onStart={startPersonal} onOpen={setEditing} onOpenRecovery={()=>document.getElementById('today-workout')?.scrollIntoView({block:'start'})}/>
      <WeekCard plan={plan} week={week} logs={data.workouts} selectedDate={data.date}/>
    </section>
    <section id="today-workout" className={`card personal-workout-plan ${isRecovery?'is-recovery-plan':''}`}>
      <Title>{todayTitle}</Title>
      <ErrorMessage error={error}/>
      {plan?.status==='needs_review'?<SafetyState message={plan.safety.message}/>:completion?<CompletedWorkout summary={completion} close={()=>setCompletion(null)} onGoHome={onGoHome}/>:sessionProps?<WorkoutSession {...sessionProps}/>:isRecovery&&todayDay?<RecoveryState day={todayDay} busy={busy||creating} onOpen={startPersonal}/>:todayDay?.exercises.length?<div className="personal-exercise-list">{todayDay.exercises.map((item,index)=>{const exercise=exerciseById.get(overrides[item.exerciseId]||item.exerciseId)||exerciseById.get(item.exerciseId);return <PlannedExercise key={item.exerciseId} item={item} exercise={exercise} index={index} onReplace={()=>cycleVariant(item)} onTechnique={setTechnique}/>})}</div>:<Empty>{words.noPlan}</Empty>}
      {!completion&&!active&&finished?<SessionLog workout={finished} onOpen={()=>setEditing(finished)}/>:null}
    </section>
    {!active&&<section className="workout-other-programs" aria-labelledby="other-programs-title">
      <div className="other-programs-head"><div><span className="eyebrow">ДОПОЛНИТЕЛЬНО</span><h2 id="other-programs-title">{words.other}</h2><p>{words.otherDescription}</p></div>{genericPrograms.length>4&&<button className="text-button other-programs-toggle" aria-expanded={showAllPrograms} onClick={()=>setShowAllPrograms(value=>!value)}>{showAllPrograms?words.hideAll:words.showAll}<ArrowRight size={14}/></button>}</div>
      {visiblePrograms.length?<div className="other-program-grid">{visiblePrograms.map(program=><article className="other-program-card" key={program.id}><span className="other-program-icon"><Activity size={17}/></span><div><h3>{program.name}</h3><small><Clock3 size={13}/>{program.minutes} {'мин'}</small><p>{program.description}</p></div><button className="text-button other-program-open" disabled={busy||creating} onClick={()=>startGeneric(program)}>{'Открыть'} <ArrowRight size={14}/></button></article>)}</div>:<p className="form-note">{words.noPrograms}</p>}
    </section>}
    {editing&&<Dialog title={editing.data.name} close={()=>setEditing(null)}><WorkoutSession workout={editing} mutate={mutate} catalogExercises={exerciseById} onTechnique={setTechnique} outsidePlan={!!todayDay&&!(editing.data.planId===plan?.id&&editing.data.trainingDayId===todayDay.id)} onCompleted={value=>{setCompletion(value);setEditing(null)}}/></Dialog>}
    {technique&&<TechniqueDialog item={technique} trainerAvatar={trainerAvatar} setTrainerAvatar={setTrainerAvatar} enableMixamoPreview={mixamoTechniquePreviewEnabled} close={()=>setTechnique(null)}/>}
  </>
}

function TodayCard({plan,day,active,finished,outsidePlan,busy,onStart,onOpen,onOpenRecovery}:{plan:TrainingPlan|undefined|null;day:TrainingDay|undefined;active:Workout|undefined;finished:Workout|undefined;outsidePlan:boolean;busy:boolean;onStart:()=>Promise<void>;onOpen:(workout:Workout)=>void;onOpenRecovery:()=>void}){
  const exerciseCount=day?.exercises.length||0
  if(active&&day&&outsidePlan)return <article className="card planned-day-external-card"><div className="planned-day-summary"><span className="eyebrow">СЕГОДНЯ ПО ПЛАНУ</span><h2>{day.recoveryDay?words.recovery:day.name}</h2><p>{day.recoveryDay?words.recoveryDescription:`${day.durationMinutes} мин · ${exerciseCount} упражнений · ${intensityLabel(day.intensity)} интенсивность`}</p></div><div className="outside-plan-status"><span>Внеплановая: <strong>{active.data.name}</strong> · в процессе</span><button className="soft-button" onClick={()=>onOpen(active)}><Play size={14}/>{words.continue}</button></div></article>
  if(!active&&!finished&&plan?.status==='active'&&day?.recoveryDay)return <article className="card recovery-today-card"><div><span className="eyebrow">{words.todayLabel}</span><h2>{words.recoveryTitle}</h2><p>{words.recoveryDescription}</p></div><div className="recovery-today-side"><RecoveryGuidance compact/><button className="soft-button recovery-open" onClick={onOpenRecovery}><Play size={14}/>{words.openRecovery}</button></div></article>
  return <article className="card workout-today personal-today-card"><div><span className="eyebrow">{words.today}</span><h2>{active?'Тренировка в процессе':finished?'Тренировка завершена':plan?.status==='needs_review'?'Сначала уточним нагрузку':day?.name||'Твой персональный ритм'}</h2><p>{plan?.status==='needs_review'?plan.safety.message:active?`${active.data.exercises.length} упражнений · ${active.data.minutes||day?.durationMinutes||0} мин`:finished?finished.data.progressRecommendation?.label||'Запись сохранена.':`${day?.durationMinutes||0} мин · ${exerciseCount} упражнений · ${intensityLabel(day?.intensity||'moderate')} интенсивность`}</p></div><span className={`round-icon ${plan?.status==='needs_review'?'yellow':'green'}`}>{plan?.status==='needs_review'?<ShieldCheck/>:<Dumbbell/>}</span>{active?<button className="primary-button" onClick={()=>onOpen(active)}><Play size={16}/>{words.continue}</button>:!finished&&plan?.status==='active'&&day&&day.exercises.length>0&&<button className="primary-button" disabled={busy} onClick={onStart}><Play size={16}/>{words.start}</button>}</article>
}
function RecoveryGuidance({compact=false}:{compact?:boolean}){return <ul className={`recovery-guidance ${compact?'is-compact':''}`}><li>{words.recoveryWalk}</li><li>{words.recoveryMobility}</li><li>{words.recoveryNoLoad}</li></ul>}
function RecoveryState({day,busy,onOpen}:{day:TrainingDay;busy:boolean;onOpen:()=>Promise<void>}){return <div className="recovery-state"><div><span className="eyebrow">{words.recovery}</span><h3>{words.recoveryTitle}</h3><p>{words.recoveryDescription}</p></div><RecoveryGuidance/>{day.exercises.length>0&&<button className="soft-button recovery-open" disabled={busy} onClick={onOpen}><Play size={14}/>{words.openRecovery}</button>}</div>}
function WeekCard({plan,week,logs,selectedDate}:{plan:TrainingPlan|undefined|null;week:TrainingPlan['currentWeek']|undefined;logs:Workout[];selectedDate:string}){return <article className="card workout-week personal-week-card"><div className="workout-week-head"><div><span className="eyebrow">ТВОЙ РИТМ</span><h2>{words.week}</h2></div><CalendarDays size={20}/></div><div className="personal-week-list">{week?.days.map(day=>{const session=logs.find(item=>item.date===day.date),status=session?.finished?'готово':session?'в процессе':words.planned,isToday=day.date===selectedDate;return <div key={day.date} className={`${day.recoveryDay?'is-recovery':''} ${isToday?'is-current':''}`}><span>{dayName(day.date)}</span><div><div className="personal-week-title"><strong>{day.recoveryDay?words.recovery:day.name}</strong>{isToday&&<b>Сегодня</b>}</div>{!day.recoveryDay&&<small>Тренировка · {day.durationMinutes} мин · {intensityLabel(day.intensity)}</small>}</div>{!day.recoveryDay&&<i>{status}</i>}</div>})||<Empty>{plan?.safety.message||words.noPlan}</Empty>}</div></article>}
function PlannedExercise({item,exercise,index,onReplace,onTechnique}:{item:TrainingDay['exercises'][number];exercise:CatalogItem|undefined;index:number;onReplace:()=>void;onTechnique:(value:{exerciseId:string;name:string;media:ExerciseMedia})=>void}){const media=exercise?.media||noMedia,detail=item.reps?`${item.sets} × ${item.reps}`:`${item.sets} × ${item.durationSeconds} с`;return <article className="personal-exercise" data-exercise-id={item.exerciseId}><span className="personal-exercise-number">{index+1}</span><div className="personal-exercise-main"><h3>{exercise?.name||'Упражнение'}</h3><p>{detail} · отдых {item.restSeconds} с</p>{exercise?.equipment?.length?<small>{equipmentLabel(exercise.equipment)}</small>:<small>Собственный вес</small>}</div><div className="personal-exercise-actions"><span className="personal-exercise-media-slot" aria-hidden="true"><Video size={14}/></span><button className="text-button" onClick={()=>onTechnique({exerciseId:item.exerciseId,name:exercise?.name||'',media})}><Video size={14}/>{words.technique}</button><button className="text-button" disabled={!item.variants.length} onClick={onReplace}><Repeat2 size={14}/>{words.replace}</button></div></article>}
function SessionLog({workout,onOpen}:{workout:Workout;onOpen:()=>void}){
  const total=workout.data.exercises.reduce((sum,item)=>sum+item.sets.length,0)
  const done=workout.data.exercises.reduce((sum,item)=>sum+item.sets.filter(set=>set.done).length,0)
  return <article className="workout-log workout-session-log">
    <span className="round-icon green">{workout.finished?<Check/>:<Activity/>}</span>
    <div><h3>{workout.data.name}</h3><p>{workout.finished?`Завершена · ${done} подходов выполнено`:`В процессе · ${done} из ${total} подходов`}</p>
      <div className="row-actions"><button className="soft-button" onClick={onOpen}>{workout.finished?'Посмотреть записи':words.continue}</button></div>
    </div>
  </article>
}
function SafetyState({message}:{message:string}){return <div className="workout-safety-state"><ShieldCheck size={22}/><div><strong>Сперва ориентируйся на ограничения специалиста</strong><p>{message}</p></div></div>}
const techniqueDialogCopy={
  viewMode:'\u0420\u0435\u0436\u0438\u043c \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430',
  technique:'\u0422\u0435\u0445\u043d\u0438\u043a\u0430',mixamo:'Mixamo \u0442\u0435\u0441\u0442',
  testTrainer:'\u0422\u0435\u0441\u0442\u043e\u0432\u044b\u0439 \u0442\u0440\u0435\u043d\u0435\u0440',mixamoTrainerChoice:'\u0412\u044b\u0431\u043e\u0440 Mixamo-\u0442\u0440\u0435\u043d\u0435\u0440\u0430',
  female:'\u0416\u0435\u043d\u0449\u0438\u043d\u0430',male:'\u041c\u0443\u0436\u0447\u0438\u043d\u0430',trainer:'\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0435\u0442:',trainerChoice:'\u0412\u044b\u0431\u043e\u0440 \u0442\u0440\u0435\u043d\u0435\u0440\u0430',
  loadingMixamo:'\u0417\u0430\u0433\u0440\u0443\u0436\u0430\u0435\u043c Mixamo Air Squat',loadingTechnique:'\u0417\u0430\u0433\u0440\u0443\u0436\u0430\u0435\u043c 3D-\u0442\u0435\u0445\u043d\u0438\u043a\u0443',
  unavailable:'\u0414\u0435\u043c\u043e\u043d\u0441\u0442\u0440\u0430\u0446\u0438\u044f \u0442\u0435\u0445\u043d\u0438\u043a\u0438 \u0441\u043a\u043e\u0440\u043e \u0431\u0443\u0434\u0435\u0442 \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u0430',fallback:'\u041f\u043e\u043a\u0430 \u043e\u0440\u0438\u0435\u043d\u0442\u0438\u0440\u0443\u0439\u0441\u044f \u043d\u0430 \u043a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u043c\u043e\u043c\u0435\u043d\u0442\u044b \u0443\u043f\u0440\u0430\u0436\u043d\u0435\u043d\u0438\u044f.',
  testEyebrow:'\u0422\u0415\u0421\u0422\u041e\u0412\u042b\u0419 \u0420\u0415\u0416\u0418\u041c \u00b7 MIXAMO',
  mixamoDescription:'\u041e\u0440\u0438\u0433\u0438\u043d\u0430\u043b\u044c\u043d\u044b\u0439 Air Squat \u0438\u0437 combined GLB: \u043c\u043e\u0434\u0435\u043b\u044c, \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044b \u0438 clip squat \u0437\u0430\u0433\u0440\u0443\u0436\u0430\u044e\u0442\u0441\u044f \u0438\u0437 \u043e\u0434\u043d\u043e\u0433\u043e \u0444\u0430\u0439\u043b\u0430.',
  testStatus:'\u0422\u0435\u0445\u043d\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0438 \u0432\u0438\u0437\u0443\u0430\u043b\u044c\u043d\u0430\u044f \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0438 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u044b. \u041f\u0440\u043e\u0432\u0435\u0440\u043a\u0430 \u0442\u0435\u0445\u043d\u0438\u043a\u0438 \u0441\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u043e\u043c \u043e\u0441\u0442\u0430\u0451\u0442\u0441\u044f \u043e\u0436\u0438\u0434\u0430\u044e\u0449\u0435\u0439.',
  keyMoments:'\u041a\u041b\u042e\u0427\u0415\u0412\u042b\u0415 \u041c\u041e\u041c\u0415\u041d\u0422\u042b',commonMistakes:'\u0427\u0410\u0421\u0422\u042b\u0415 \u041e\u0428\u0418\u0411\u041a\u0418'
}
export function TechniqueDialog({item,trainerAvatar,setTrainerAvatar,close,enableMixamoPreview=false,initialViewerMode='technique',startPaused=false}:{item:{exerciseId:string;name:string;media:ExerciseMedia};trainerAvatar:TrainerAvatar;setTrainerAvatar:(avatar:TrainerAvatar)=>void;close:()=>void;enableMixamoPreview?:boolean;initialViewerMode?:'technique'|'mixamo';startPaused?:boolean}){
  const [reduced,setReduced]=useState(()=>typeof window!=='undefined'&&window.matchMedia('(prefers-reduced-motion: reduce)').matches)
  const [viewerMode,setViewerMode]=useState<'technique'|'mixamo'>(initialViewerMode)
  useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReduced(query.matches);query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[])
  const squatVideo=item.exerciseId==='squat'?getSquatTechniqueVideo(trainerAvatar):null
  const asset=getExercise3DAsset(item.exerciseId,trainerAvatar)
  const isMixamoSquatPreview=enableMixamoPreview&&item.exerciseId==='squat'
  const mixamoAsset=isMixamoSquatPreview?getMixamoAirSquatTestAsset(trainerAvatar):null
  const showVideo=!reduced&&!!item.media.shortVideoUrl
  const techniqueContent=getExerciseTechnique(item.exerciseId)
  const displayName=techniqueExerciseName(item)
  return <Dialog className="technique-dialog" title={`${words.technique}: ${displayName}`} close={close}>
    {enableMixamoPreview&&<div className="technique-view-switch" role="group" aria-label={techniqueDialogCopy.viewMode}>
      <button className={viewerMode==='technique'?'is-active':''} type="button" aria-pressed={viewerMode==='technique'} onClick={()=>setViewerMode('technique')}>{techniqueDialogCopy.technique}</button>
      {isMixamoSquatPreview&&<button className={viewerMode==='mixamo'?'is-active':''} type="button" aria-pressed={viewerMode==='mixamo'} onClick={()=>setViewerMode('mixamo')}>{techniqueDialogCopy.mixamo}</button>}
    </div>}
    {viewerMode==='mixamo'&&mixamoAsset?<div className="trainer-avatar-switch mixamo-avatar-switch"><span>{techniqueDialogCopy.testTrainer}</span><div role="group" aria-label={techniqueDialogCopy.mixamoTrainerChoice}>{(['female','male'] as TrainerAvatar[]).map(avatar=><button key={avatar} type="button" aria-pressed={trainerAvatar===avatar} className={trainerAvatar===avatar?'is-active':''} onClick={()=>setTrainerAvatar(avatar)}>{getMixamoAirSquatTestAsset(avatar).label}</button>)}</div></div>:squatVideo?<div className="trainer-avatar-switch"><span>{techniqueDialogCopy.trainer}</span><div role="group" aria-label={techniqueDialogCopy.trainerChoice}>{(['female','male'] as TrainerAvatar[]).map(avatar=><button key={avatar} type="button" aria-pressed={trainerAvatar===avatar} className={trainerAvatar===avatar?'is-active':''} onClick={()=>setTrainerAvatar(avatar)}>{avatar==='female'?techniqueDialogCopy.female:techniqueDialogCopy.male}</button>)}</div></div>:null}
    <div className={`technique-dialog-layout ${viewerMode==='mixamo'?'is-mixamo-review':''}`}><div className="exercise-technique-video" data-exercise-id={item.exerciseId}>
      {viewerMode==='mixamo'&&mixamoAsset?<Suspense fallback={<div className="exercise-3d-skeleton" aria-label={techniqueDialogCopy.loadingMixamo}/>}><Exercise3DViewer key={`mixamo-air-squat:${trainerAvatar}:${mixamoAsset.modelUrl}`} {...mixamoAsset} cameraPosition={[4.25,1.25,.33]} controlsTarget={[0,0,0]} lightingPreset="mixamo-review" startPaused={startPaused}/></Suspense>:squatVideo?<TechniqueVideoViewer key={`${trainerAvatar}:${squatVideo.label}`} asset={squatVideo} reducedMotion={reduced}/>:asset?.ready?<Suspense fallback={<div className="exercise-3d-skeleton" aria-label={techniqueDialogCopy.loadingTechnique}/>}><Exercise3DViewer key={`${asset.modelUrl}:${asset.animationUrl}:${asset.animationClip}`} {...asset}/></Suspense>:showVideo?<video autoPlay muted playsInline loop controls={false} preload="metadata" poster={item.media.posterUrl||undefined}><source src={item.media.shortVideoUrl||undefined} type="video/mp4"/></video>:item.media.posterUrl?<img src={item.media.posterUrl} alt=""/>:asset?<div className="exercise-3d-fallback"><img src={asset.posterUrl} alt=""/><div><strong>{techniqueDialogCopy.unavailable}</strong><p>{techniqueDialogCopy.fallback}</p></div></div>:<div className="exercise-technique-placeholder"><Video size={28}/><strong>{techniqueDialogCopy.unavailable}</strong><p>{techniqueDialogCopy.fallback}</p></div>}
    </div><aside className="technique-guidance">
      {viewerMode==='mixamo'&&mixamoAsset?<><span className="eyebrow">{techniqueDialogCopy.testEyebrow}</span><h3>{mixamoAsset.label}</h3><p className="technique-preview-note">{techniqueDialogCopy.mixamoDescription}</p><p className="mixamo-technical-id">Mixamo ID: {mixamoAsset.technicalLabel}</p><ul>{techniqueContent.cues.map(tip=><li key={tip}>{tip}</li>)}</ul><p className="mixamo-technique-status">{techniqueDialogCopy.testStatus}</p></>:<><span className="eyebrow">{techniqueDialogCopy.keyMoments}</span><h3>{displayName}</h3><ul>{techniqueContent.cues.map(tip=><li key={tip}>{tip}</li>)}</ul>{techniqueContent.mistakes?.length?<section className="technique-mistakes"><span className="eyebrow">{techniqueDialogCopy.commonMistakes}</span><ul>{techniqueContent.mistakes.map(mistake=><li key={mistake}>{mistake}</li>)}</ul></section>:null}{techniqueContent.safetyNote?<p>{techniqueContent.safetyNote}</p>:null}</>}
    </aside></div>
  </Dialog>
}

function WorkoutSession({workout,mutate,catalogExercises,onTechnique,outsidePlan,onCompleted}:{workout:Workout;mutate:Mutate;catalogExercises:Map<string,CatalogItem>;onTechnique:(value:TechniqueItem)=>void;outsidePlan:boolean;onCompleted:(value:WorkoutCompletion)=>void}){
  const [exercises,setExercises]=useState<ExerciseLog[]>(structuredClone(workout.data.exercises)),[activeIndex,setActiveIndex]=useState(0),[saving,setSaving]=useState(false),[error,setError]=useState(''),[feedbackOpen,setFeedbackOpen]=useState(false),[feedback,setFeedback]=useState<'easy'|'normal'|'hard'|null>(null),[painOrDiscomfort,setPainOrDiscomfort]=useState<boolean|null>(null),[restRemaining,setRestRemaining]=useState<number|null>(null),[restNextSet,setRestNextSet]=useState<number|null>(null),[replacementOpen,setReplacementOpen]=useState(false),[rpeHelpOpen,setRpeHelpOpen]=useState(false),[confirmNext,setConfirmNext]=useState(false)
  const edited=useRef(false),mutateRef=useRef(mutate),restEndsAt=useRef<number|null>(null),exercise=exercises[activeIndex],total=exercises.reduce((sum,item)=>sum+item.sets.length,0),doneSets=exercises.reduce((sum,item)=>sum+item.sets.filter(set=>set.done).length,0),allDone=total>0&&doneSets===total
  useEffect(()=>{mutateRef.current=mutate},[mutate])
  useEffect(()=>{if(!edited.current){edited.current=true;return}const timer=window.setTimeout(async()=>{if(feedbackOpen)return;setSaving(true);setError('');try{await mutateRef.current('/api/workouts','PUT',{id:workout.id,date:workout.date,exercises,finished:false})}catch(reason){setError(errorText(reason))}finally{setSaving(false)}},550);return()=>window.clearTimeout(timer)},[exercises,workout.id,workout.date,feedbackOpen])
  useEffect(()=>{if(restRemaining===null||restEndsAt.current===null)return;let frame=0;const tick=()=>{const remaining=Math.max(0,(restEndsAt.current!-performance.now())/1000);if(remaining<=0){restEndsAt.current=null;setRestRemaining(null);return}setRestRemaining(remaining);frame=window.requestAnimationFrame(tick)};frame=window.requestAnimationFrame(tick);return()=>window.cancelAnimationFrame(frame)},[restRemaining===null])
  useEffect(()=>{restEndsAt.current=null;setRestRemaining(null);setRestNextSet(null);setReplacementOpen(false);setRpeHelpOpen(false);setConfirmNext(false)},[activeIndex,exercise?.exerciseId])
  if(!exercise)return <Empty>В этой тренировке пока нет упражнений.</Empty>
  const catalogExercise=catalogExercises.get(exercise.exerciseId),media=catalogExercise?.media||noMedia
  const alternatives=exercise.alternatives?.length?exercise.alternatives:(exercise.variants?.length?exercise.variants:catalogExercise?.variants||[]).map(exerciseId=>({exerciseId,reason:'same_pattern' as const,movementPattern:catalogExercise?.movementPattern||'same_pattern'}))
  const candidateIds=[...new Set(alternatives.map(item=>item.exerciseId))].filter(id=>id!==exercise.exerciseId)
  const variants=candidateIds.map(id=>catalogExercises.get(id)).filter((item):item is CatalogItem=>!!item)
  const hasCompletedSets=exercise.sets.some(set=>set.done)
  const hasUnfinishedSets=exercise.sets.some(set=>!set.done)
  const detail=exercise.unit==='seconds'?`${exercise.sets.length} × ${exercise.sets[0]?.reps||0} с`:`${exercise.sets.length} × ${exercise.sets[0]?.reps||0}`
  const isTimedExercise=exercise.unit==='seconds',equipment=exercise.equipment||[],usesDumbbells=equipment.some(item=>item==='dumbbells'||item==='adjustable_dumbbells'),usesExternalWeight=equipment.some(item=>['barbell','kettlebell','machines','weight_plates','external_weight'].includes(item)),weightLabel=isTimedExercise?null:usesDumbbells?'Вес гантелей, кг':usesExternalWeight?'Вес, кг':equipment.length===0?'Доп. вес, кг':null
  const change=(setIndex:number,key:'reps'|'weight'|'done',value:number|boolean)=>setExercises(items=>items.map((item,index)=>index===activeIndex?{...item,sets:item.sets.map((set,current)=>current===setIndex?{...set,[key]:value}:set)}:item))
  const toggleSet=(setIndex:number)=>{const isDone=exercise.sets[setIndex].done,nextSet=exercise.sets.findIndex((set,index)=>index>setIndex&&!set.done);change(setIndex,'done',!isDone);if(!isDone&&nextSet>=0&&exercise.restSeconds){restEndsAt.current=performance.now()+exercise.restSeconds*1000;setRestRemaining(exercise.restSeconds);setRestNextSet(nextSet+1)}else if(isDone){restEndsAt.current=null;setRestRemaining(null);setRestNextSet(null)}}
  const replaceExercise=(candidate:CatalogItem)=>{setExercises(items=>items.map((item,index)=>index===activeIndex?{...item,exerciseId:candidate.id,name:candidate.name,unit:candidate.unit||item.unit,equipment:candidate.equipment||[],alternatives:(candidate.variants||[]).map(exerciseId=>({exerciseId,reason:'same_pattern' as const,movementPattern:candidate.movementPattern||'same_pattern'})),variants:undefined}:item));setReplacementOpen(false);restEndsAt.current=null;setRestRemaining(null);setRestNextSet(null)}
  const goNext=()=>{setConfirmNext(false);setActiveIndex(value=>value+1)}
  const finish=async()=>{if(!feedback||painOrDiscomfort===null)return;setSaving(true);setError('');const rpe={easy:4,normal:6,hard:8}[feedback],started=Date.parse(workout.data.startedAt||''),elapsedMinutes=Number.isFinite(started)?Math.max(1,Math.round((Date.now()-started)/60000)):workout.data.minutes||0,totalVolumeKg=Math.round(exercises.reduce((sum,item)=>sum+item.sets.reduce((volume,set)=>volume+(set.done?(Number(set.weight)||0)*(Number(set.reps)||0):0),0),0));try{await mutate('/api/workouts','PUT',{id:workout.id,date:workout.date,exercises,finished:true,feedback:{rpe,perceivedDifficulty:feedback,allSetsCompleted:allDone,painOrDiscomfort}});onCompleted({name:workout.data.name,elapsedMinutes,completedExercises:exercises.filter(item=>item.sets.some(set=>set.done)).length,totalExercises:exercises.length,completedSets:doneSets,totalSets:total,totalVolumeKg,feedbackLabel:{easy:'Легко',normal:'Нормально',hard:'Тяжело'}[feedback],painOrDiscomfort})}catch(reason){setError(errorText(reason))}finally{setSaving(false)}}
  if(feedbackOpen)return <section className="workout-feedback"><span className="eyebrow">ПОСЛЕ ТРЕНИРОВКИ</span><h3>Тренировка завершена</h3><p className="workout-feedback-summary">Упражнения: {exercises.filter(item=>item.sets.some(set=>set.done)).length} из {exercises.length} · Подходы: {doneSets} из {total}</p><h4>Как прошла тренировка?</h4><div className="workout-feedback-options" role="group" aria-label="Субъективная оценка тренировки">{([['easy','Легко'],['normal','Нормально'],['hard','Тяжело']] as const).map(([value,label])=><button type="button" key={value} className={feedback===value?'is-selected':''} aria-pressed={feedback===value} onClick={()=>setFeedback(value)}>{label}</button>)}</div><h4>Была боль или дискомфорт?</h4><div className="workout-feedback-options is-binary" role="group" aria-label="Была боль или дискомфорт">{([[false,'Нет'],[true,'Да']] as const).map(([value,label])=><button type="button" key={label} className={painOrDiscomfort===value?'is-selected':''} aria-pressed={painOrDiscomfort===value} onClick={()=>setPainOrDiscomfort(value)}>{label}</button>)}</div><p className="workout-feedback-note">Ответ сохраним, чтобы в будущем точнее адаптировать рекомендации.</p><div className="dialog-actions"><button className="soft-button" onClick={()=>setFeedbackOpen(false)}>Назад</button><button className="primary-button" disabled={saving||!feedback||painOrDiscomfort===null} onClick={finish}>Сохранить и завершить</button></div><ErrorMessage error={error}/></section>
  return <div className="workout-live-form">
    <div className="workout-live-top"><div><span>{outsidePlan?'Внеплановая тренировка':'Тренировка в процессе'}</span><strong>{workout.data.name}</strong></div><div className="workout-live-progress"><small>{workout.data.intensity&&intensityLabel(workout.data.intensity)} · {workout.data.minutes||0} мин</small><span>{activeIndex+1} из {exercises.length} упражнений · {doneSets} из {total} подходов</span></div></div>
    <div className="workout-live-exercise"><div className="workout-live-exercise-head"><span>Упражнение {activeIndex+1} из {exercises.length}</span><h3>{exercise.name||catalogExercise?.name||'Упражнение'}</h3><p>{detail} · отдых {exercise.restSeconds||0} с · {intensityLabel(workout.data.intensity||'moderate')} интенсивность</p><div className="workout-live-exercise-meta"><span className="workout-rpe">{rpeLabel(exercise.targetRpe)} · RPE {exercise.targetRpe||'—'} <button type="button" aria-label="Пояснение к RPE" aria-expanded={rpeHelpOpen} onClick={()=>setRpeHelpOpen(value=>!value)}><CircleHelp size={13} strokeWidth={2}/></button></span>{rpeHelpOpen&&<span className="workout-rpe-tooltip" role="tooltip">{rpeHint(exercise.targetRpe)}</span>}<small>{exercise.equipment?.length?equipmentLabel(exercise.equipment):'Собственный вес'}</small></div><div className="workout-live-exercise-actions"><button type="button" className="text-button workout-technique-button" onClick={()=>onTechnique({exerciseId:exercise.exerciseId,name:exercise.name||catalogExercise?.name||'',media})}><Video size={14}/>{words.technique}</button><button type="button" className="text-button" disabled={!variants.length||hasCompletedSets} title={hasCompletedSets?'Замену можно выбрать до первого выполненного подхода.':undefined} onClick={()=>setReplacementOpen(value=>!value)}><Repeat2 size={14}/>{words.replace}</button></div>{replacementOpen&&<div className="workout-replacement"><span>Выбери замену</span><div>{variants.map(candidate=><button type="button" key={candidate.id} onClick={()=>replaceExercise(candidate)}>{candidate.name}</button>)}</div></div>}</div>
      <p className="workout-set-note">Фактические вес и повторы сохраняются отдельно от плана.</p><div className={`workout-set-table ${weightLabel?'':'is-unweighted'}`}><div className="workout-set-head"><span>Подход</span>{weightLabel&&<span>{weightLabel}</span>}<span>{exercise.unit==='seconds'?'Секунды':'Повторы'}</span><span>Готово</span></div>{exercise.sets.map((set,index)=><div className={`workout-live-set ${set.done?'is-done':''}`} key={index}><b>{index+1}</b>{weightLabel&&<input aria-label={`${weightLabel} в подходе ${index+1}`} type="number" min="0" max="500" step="0.5" value={set.weight||''} placeholder="кг" onChange={event=>change(index,'weight',Number(event.target.value))}/>}<input aria-label={`Фактические ${exercise.unit==='seconds'?'секунды':'повторы'} в подходе ${index+1}`} type="number" min="1" max="3600" value={set.reps} onChange={event=>change(index,'reps',Number(event.target.value))}/><button type="button" className="workout-set-toggle" aria-label={`Отметить подход ${index+1} выполненным`} aria-pressed={set.done} onClick={()=>toggleSet(index)}>{set.done?<Check size={15}/>:null}</button></div>)}</div>
    </div>
    {restRemaining!==null&&<div className="workout-rest" role="status"><div><span>Отдых</span><strong>{clock(restRemaining)}</strong>{restNextSet!==null&&<small>Следующий подход: {restNextSet} из {exercise.sets.length}</small>}</div><div className="workout-rest-progress" aria-hidden="true"><b style={{width:`${Math.max(0,Math.min(100,restRemaining/(exercise.restSeconds||1)*100))}%`}}/></div><button type="button" className="text-button" onClick={()=>{restEndsAt.current=null;setRestRemaining(null);setRestNextSet(null)}}>Пропустить</button></div>}
    {confirmNext&&<div className="workout-next-confirm" role="alertdialog" aria-label="Подтвердить переход к следующему упражнению"><p>Перейти дальше и оставить подходы незавершёнными?</p><div><button type="button" className="text-button" onClick={()=>setConfirmNext(false)}>Остаться</button><button type="button" className="soft-button" onClick={goNext}>Перейти дальше</button></div></div>}
    <div className="workout-live-navigation"><button type="button" className="soft-button" disabled={activeIndex===0} onClick={()=>setActiveIndex(value=>value-1)}><ChevronLeft size={15}/>Назад</button>{activeIndex<exercises.length-1?<button type="button" className="primary-button" onClick={()=>hasUnfinishedSets?setConfirmNext(true):goNext()}>Следующее <ChevronRight size={15}/></button>:<button type="button" className="primary-button" disabled={!allDone||saving} onClick={()=>setFeedbackOpen(true)}>Завершить тренировку <Check size={15}/></button>}</div><p className="workout-autosave">✓ {words.progress}</p><ErrorMessage error={error}/>
  </div>
}

function CompletedWorkout({summary,close,onGoHome}:{summary:WorkoutCompletion;close:()=>void;onGoHome?:()=>void}){return <section className="workout-complete"><span className="round-icon green"><Check/></span><div><span className="eyebrow">ГОТОВО</span><h3>Тренировка завершена</h3><p>{summary.name}</p><div className="workout-completion-stats"><span>Время <b>{summary.elapsedMinutes} мин</b></span><span>Упражнения <b>{summary.completedExercises} из {summary.totalExercises}</b></span><span>Подходы <b>{summary.completedSets} из {summary.totalSets}</b></span>{summary.totalVolumeKg>0&&<span>Объём <b>{summary.totalVolumeKg.toLocaleString('ru-RU')} кг</b></span>}<span>Самочувствие <b>{summary.feedbackLabel}</b></span><span>{summary.painOrDiscomfort?'Есть дискомфорт':'Без дискомфорта'}</span></div></div><button className="primary-button" onClick={onGoHome||close}>Вернуться к моему дню</button></section>}
