import { useState } from 'react'
import { Activity, CalendarDays, Check, Clock3, Dumbbell, Play, Plus } from 'lucide-react'
import { type CatalogItem, type ExerciseLog, type Mutate, type State, type Workout } from '../api'
import { Dialog, Empty, ErrorMessage, errorText, Title } from './ui'
export default function Workouts({data,mutate,busy}:{data:State;mutate:Mutate;busy:boolean}){
  const [editing,setEditing]=useState<Workout|null>(null),[error,setError]=useState(''),[creating,setCreating]=useState(false)
  const programs=data.catalog.filter(i=>i.kind==='program'),logs=data.workouts.filter(w=>w.date===data.date)
  const start=async(program:CatalogItem)=>{setCreating(true);setError('');try{await mutate('/api/workouts','PUT',{id:crypto.randomUUID(),programId:program.id,date:data.date,finished:false})}catch(reason){setError(errorText(reason))}finally{setCreating(false)}}
  return <><WorkoutOverview data={data} logs={logs} programs={programs} busy={busy||creating} start={start} open={workout=>setEditing(workout)}/><div className="journal-grid workout-journal"><section className="card"><Title>Тренировки за день</Title><ErrorMessage error={error}/>{logs.length?logs.map(w=><article className="workout-log" key={w.id}><span className="round-icon green">{w.finished?<Check/>:<Activity/>}</span><div><h3>{w.data.name}</h3><p>{w.finished?'Завершена':'В процессе'} · {w.data.exercises.reduce((n,e)=>n+e.sets.filter(s=>s.done).length,0)} подходов выполнено</p><div className="row-actions"><button className="soft-button" onClick={()=>setEditing(w)}>{w.finished?'Посмотреть записи':'Продолжить'}</button><button className="text-button danger" disabled={busy} onClick={()=>mutate(`/api/workouts/${w.id}`,'DELETE',{}).catch(e=>setError(errorText(e)))}>Удалить</button></div></div></article>):<Empty>Выбери программу и начни своё занятие. Записи подходов сохраняются в аккаунте.</Empty>}<h3 className="subheading">Предыдущие занятия</h3>{data.workouts.filter(w=>w.date!==data.date).slice(0,12).map(w=><button className="history-workout" key={w.id} onClick={()=>setEditing(w)}><span>{w.date}</span><strong>{w.data.name}</strong><small>{w.finished?'Завершена':'Не завершена'}</small></button>)}</section><section className="card workout-programs"><Title>Программы</Title><p className="form-note">Выбери программу под свой ритм. Нагрузку и количество подходов можно менять в любой момент.</p><div className="program-grid">{programs.map(p=><article className="program-card" key={p.id}><div className="program-cover"><Activity size={25}/><h3>{p.name}</h3><span><Clock3 size={14}/>{p.minutes} минут</span></div><p>{p.description}</p><ul>{p.exercises?.map((e,i)=><li key={i}>{data.catalog.find(c=>c.id===e.exerciseId)?.name} · {e.sets} × {e.reps}</li>)}</ul><button className="primary-button" disabled={busy||creating} onClick={()=>start(p)}>Начать тренировку <Plus size={16}/></button></article>)}</div><h3 className="subheading">Упражнения</h3>{data.catalog.filter(i=>i.kind==='exercise').map(e=><details className="exercise-detail" key={e.id}><summary>{e.name}</summary><p>{e.muscle} · {e.description}</p></details>)}</section>{editing&&<Dialog title={editing.data.name} close={()=>setEditing(null)}><WorkoutForm workout={editing} mutate={mutate} done={()=>setEditing(null)}/></Dialog>}</div></>
}

function WorkoutOverview({data,logs,programs,busy,start,open}:{data:State;logs:Workout[];programs:CatalogItem[];busy:boolean;start:(program:CatalogItem)=>Promise<void>;open:(workout:Workout)=>void}) {
  const active=logs.find(workout=>!workout.finished),finished=logs.find(workout=>workout.finished),current=active||finished
  const total=current?.data.exercises.reduce((sum,exercise)=>sum+exercise.sets.length,0)||0
  const done=current?.data.exercises.reduce((sum,exercise)=>sum+exercise.sets.filter(set=>set.done).length,0)||0
  const quick=programs.find(program=>program.id==='quick-start')||programs[0]
  const dates=[0,2,4].map(offset=>{const value=new Date(`${data.date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+offset);return value.toISOString().slice(0,10)})
  const suggestions=[programs.find(program=>program.id==='upper-body'),programs.find(program=>program.id==='lower-body'),programs.find(program=>program.id==='full-body')].filter(Boolean) as CatalogItem[]
  return <section className="workout-overview"><article className="card workout-today"><div><span className="eyebrow">ТРЕНИРОВКА НА СЕГОДНЯ</span><h2>{active?'В процессе':finished?'Занятие завершено':'Время для движения'}</h2><p>{active?`${done} из ${total} подходов выполнено`:finished?`${finished.data.name} сохранена в истории.`:'Выбери программу или начни с короткого занятия.'}</p></div><span className={`round-icon ${finished?'green':'purple'}`}>{finished?<Check/>:<Dumbbell/>}</span>{current&&<><div className="workout-today-progress"><span>{current.data.name}</span><b>{total?Math.round(done/total*100):0}%</b></div><i><b style={{width:`${total?done/total*100:0}%`}}/></i></>}{active?<button className="primary-button" onClick={()=>open(active)}><Play size={16}/>Продолжить</button>:quick&&<button className="primary-button" disabled={busy} onClick={()=>start(quick)}><Play size={16}/>{data.date>data.today?'Запланировать':'Начать тренировку'}</button>}</article><article className="card workout-week"><div className="workout-week-head"><div><span className="eyebrow">ТВОЙ РИТМ</span><h2>План на неделю</h2></div><CalendarDays size={20}/></div><div className="workout-week-list">{dates.map((date,index)=>{const planned=suggestions[index],complete=data.workouts.some(workout=>workout.date===date&&workout.finished);return <div key={date}><span>{index===0?'Сегодня':new Intl.DateTimeFormat('ru-RU',{weekday:'short',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`))}</span><strong>{planned?.name||'Своя тренировка'}</strong>{complete?<Check size={15}/>:<i>{planned?.minutes||20} мин</i>}</div>})}</div></article></section>
}

function WorkoutForm({workout,mutate,done}:{workout:Workout;mutate:Mutate;done:()=>void}){
  const [exercises,setExercises]=useState<ExerciseLog[]>(structuredClone(workout.data.exercises)),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const allDone=exercises.every(e=>e.sets.every(s=>s.done))
  function change(i:number,j:number,key:string,value:number|boolean){setExercises(rows=>rows.map((e,n)=>n===i?{...e,sets:e.sets.map((s,k)=>k===j?{...s,[key]:value}:s)}:e))}
  return <form className="workspace-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await mutate('/api/workouts','PUT',{id:workout.id,date:f.get('date'),exercises,finished:f.get('finished')==='on'});done()}catch(e){setError(errorText(e))}finally{setBusy(false)}}}><label>Дата занятия<input name="date" type="date" defaultValue={workout.date} required/></label>{exercises.map((e,i)=><section className="set-editor" key={i}><h3>{e.name}</h3>{e.sets.map((s,j)=><div className="set-row" key={j}><span>{j+1}</span><label>{e.unit==='seconds'?'Секунды':'Повторы'}<input type="number" min={1} max={3600} value={s.reps} required onChange={v=>change(i,j,'reps',Number(v.target.value))}/></label><label>Вес, кг<input type="number" min={0} max={500} step="0.5" value={s.weight} required onChange={v=>change(i,j,'weight',Number(v.target.value))}/></label><label className="set-done"><input type="checkbox" checked={s.done} onChange={v=>change(i,j,'done',v.target.checked)}/>Готово</label><button type="button" className="text-button danger" aria-label={`Убрать подход ${j+1} упражнения ${e.name}`} disabled={e.sets.length===1} onClick={()=>setExercises(rows=>rows.map((r,n)=>n===i?{...r,sets:r.sets.filter((_,k)=>k!==j)}:r))}>×</button></div>)}<button type="button" className="text-button" disabled={e.sets.length>=20} onClick={()=>setExercises(rows=>rows.map((r,n)=>n===i?{...r,sets:[...r.sets,{reps:12,weight:0,done:false}]}:r))}>+ Подход</button></section>)}<label className="consent"><input name="finished" type="checkbox" defaultChecked={workout.finished} disabled={!allDone}/>Завершить тренировку</label>{!allDone&&<small>Для завершения отметь выполненные подходы. Промежуточные записи можно сохранить в любой момент.</small>}<ErrorMessage error={error}/><button className="primary-button" disabled={busy}>Сохранить тренировку</button></form>
}
