import { useEffect, useRef, useState, type ReactNode } from 'react'
import { Activity, ArrowDownRight, ArrowRight, Bell, Camera, ChartNoAxesColumnIncreasing, Check, ChevronDown, ChevronLeft, ChevronRight, Clock3, Droplets, Dumbbell, Flame, Flag, Footprints, Heart, House, Leaf, Menu, Moon, Plus, Search, ShoppingBasket, ShoppingCart, Sprout, UserRound, Utensils, Weight, X } from 'lucide-react'

const meals = [
  { name: 'Завтрак', dish: 'Овсяная каша с ягодами и орехами', kcal: 420, p: 16, f: 14, c: 58, image: 'breakfast', ingredients: 'Овсяные хлопья · 60 г, молоко · 150 мл, ягоды · 80 г, орехи · 15 г', recipe: 'Сварите хлопья на молоке до мягкости. Добавьте ягоды и измельчённые орехи перед подачей.' },
  { name: 'Обед', dish: 'Куриная грудка с гречкой и овощами', kcal: 520, p: 42, f: 12, c: 52, image: 'lunch', ingredients: 'Куриная грудка · 150 г, гречка · 60 г, овощи · 150 г', recipe: 'Отварите гречку. Запеките куриную грудку до полной готовности и подайте с овощами.' },
  { name: 'Ужин', dish: 'Лосось с киноа и брокколи', kcal: 480, p: 34, f: 18, c: 36, image: 'dinner', ingredients: 'Лосось · 150 г, киноа · 50 г, брокколи · 150 г', recipe: 'Сварите киноа, приготовьте брокколи на пару. Запеките лосось до готовности и подайте вместе.' },
  { name: 'Перекус', dish: 'Греческий йогурт с ягодами', kcal: 330, p: 20, f: 6, c: 34, image: 'snack', ingredients: 'Греческий йогурт · 200 г, ягоды · 100 г, гранола · 30 г', recipe: 'Выложите йогурт в миску, добавьте ягоды и посыпьте гранолой.' },
]
const exercises = [ ['Приседания с гантелями', '3 × 12', 'Ноги и ягодицы'], ['Жим гантелей лёжа', '3 × 10', 'Грудь и руки'], ['Тяга гантели в наклоне', '3 × 12 на каждую руку', 'Спина'], ['Планка', '3 × 45 секунд', 'Мышцы кора'] ]
const groceries = [['🥦', 'Брокколи', '600 г'], ['🍗', 'Куриная грудка', '800 г'], ['🍌', 'Бананы', '5 шт.'], ['🍅', 'Помидоры', '500 г'], ['🌾', 'Овсяные хлопья', '400 г'], ['🥛', 'Йогурт', '800 г'], ['🥬', 'Зелень', '1 пучок']]
const nav = [{ label: 'Главная', icon: House, id: 'home' }, { label: 'Питание', icon: Utensils, id: 'nutrition' }, { label: 'Тренировки', icon: Activity, id: 'workout' }, { label: 'Прогресс', icon: ChartNoAxesColumnIncreasing, id: 'progress' }, { label: 'Привычки', icon: Heart, id: 'habits' }, { label: 'Покупки', icon: ShoppingCart, id: 'shopping' }, { label: 'Профиль', icon: UserRound, id: 'profile' }]
type Saved = { name: string; weight: number; target: number; habits: boolean[]; checked: number[]; workout: number[]; date: string }
const today = () => new Date().toLocaleDateString('en-CA')
const initial: Saved = { name: 'Анна', weight: 68.2, target: 60, habits: [true, true, false, true, false], checked: [], workout: [], date: today() }
function readState(): Saved {
  try {
    const v = JSON.parse(localStorage.getItem('telo365-demo-v1') || 'null')
    if (!v || typeof v.name !== 'string' || !Number.isFinite(v.weight) || !Number.isFinite(v.target) || v.weight < 30 || v.weight > 300 || v.target < 30 || v.target > 300 || !Array.isArray(v.habits) || v.habits.length !== 5 || !v.habits.every((x: unknown) => typeof x === 'boolean') || !Array.isArray(v.checked) || !Array.isArray(v.workout)) return initial
    return { ...initial, ...v, ...(v.date !== today() ? { habits: [false, false, false, false, false], workout: [], date: today() } : {}) }
  } catch { return initial }
}
const number = (n: number) => n.toLocaleString('ru-RU', { maximumFractionDigits: 1 })
function Logo() { return <div className="logo"><Sprout aria-hidden="true" /><span>TELO<b>365</b></span></div> }
function SectionTitle({ title, onClick, children }: { title: string; onClick?: () => void; children?: ReactNode }) { return <div className="section-title"><h2>{title}</h2>{children || (onClick && <button className="text-button" onClick={onClick}>Все <ChevronRight size={15} /></button>)}</div> }
function Modal({ title, children, close }: { title: string; children: ReactNode; close: () => void }) {
  const ref = useRef<HTMLDialogElement>(null)
  useEffect(() => { const previous = document.activeElement as HTMLElement; ref.current?.showModal(); return () => { previous?.focus() } }, [])
  return <dialog ref={ref} onCancel={close} onClick={e => { if (e.target === ref.current) close() }}><div className="dialog-head"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Закрыть"><X /></button></div>{children}</dialog>
}

export default function App() {
  const [saved, setSaved] = useState<Saved>(readState)
  const [modal, setModal] = useState<string | null>(null)
  const [active, setActive] = useState('home')
  const [menu, setMenu] = useState(false)
  const [query, setQuery] = useState('')
  const [tab, setTab] = useState('Вес')
  const [toast, setToast] = useState('')
  const [storageError, setStorageError] = useState(false)
  useEffect(() => { try { localStorage.setItem('telo365-demo-v1', JSON.stringify(saved)); setStorageError(false) } catch { setStorageError(true) } }, [saved])
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(''), 3500); return () => clearTimeout(id) }, [toast])
  function navigate(id: string) { setActive(id); setMenu(false); if (id === 'profile') setModal('profile'); else document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'center' }) }
  function toggleHabit(index: number) { setSaved(s => ({ ...s, habits: s.habits.map((v, i) => i === index ? !v : v) })) }
  const complete = saved.habits.filter(Boolean).length
  const results = [...meals.map((m, i) => ({ label: m.dish, type: m.name, action: () => setModal(`meal-${i}`) })), ...nav.slice(1).map(n => ({ label: n.label, type: 'Раздел', action: () => navigate(n.id) })), ...groceries.map(g => ({ label: g[1], type: 'Продукт', action: () => setModal('shopping') }))].filter(r => r.label.toLowerCase().includes(query.trim().toLowerCase())).slice(0, 6)
  const habitRows = [{ icon: Droplets, name: 'Вода', text: '2,1 из 2,5 л', color: 'blue' }, { icon: Moon, name: 'Сон', text: '7 из 8 часов', color: 'purple' }, { icon: Footprints, name: 'Шаги', text: '8 420 из 10 000', color: 'green' }, { icon: Heart, name: 'Питание', text: '4 из 4 приёмов', color: 'green' }, { icon: Dumbbell, name: 'Тренировка', text: saved.workout.length === 4 ? 'План выполнен' : 'Отметьте после занятия', color: 'green' }]
  const weights = [73, 72.5, 71.5, 70.5, 70, 69.4, 69.1, 68.5, 68.4, 68.1, saved.weight]
  const chartValues = tab === 'Калории' ? [1920, 1830, 2100, 1800, 1900, 1780, 1820, 1950, 1870, 1810, 1750] : weights
  const chartMin = tab === 'Калории' ? 1400 : Math.min(60, ...weights) - (saved.weight < 60 ? 2 : 0)
  const chartMax = tab === 'Калории' ? 2400 : Math.max(80, ...weights) + (saved.weight > 80 ? 2 : 0)
  const points = chartValues.map((w, i) => `${38 + i * 25.4},${150 - (w - chartMin) / (chartMax - chartMin) * 128}`).join(' ')
  return <div className="app-shell">
    {menu && <button className="menu-scrim" aria-label="Закрыть меню" onClick={() => setMenu(false)} />}
    <aside className={`sidebar ${menu ? 'is-open' : ''}`}>
      <a className="brand-link" href="#home" onClick={() => navigate('home')}><Logo /><span className="brand-caption">ЗДОРОВЫЕ ЛЮДИ<br />СЧАСТЛИВЕЕ</span></a>
      <nav aria-label="Основная навигация">{nav.map(n => <button key={n.id} className={active === n.id ? 'active' : ''} onClick={() => navigate(n.id)}><n.icon size={22} /><span>{n.label}</span>{active === n.id && <span className="nav-dot" />}</button>)}</nav>
      <div className="sidebar-note"><div className="note-top"><span className="eyebrow">ШАГ ЗА ШАГОМ</span><p>Большие цели<br />начинаются<br />с маленьких<br />действий.</p><span className="small-line" /></div><div className="note-bottom"><strong>TELO365</strong><p>Твоё тело. Каждый день.</p><span>telo365.ru</span></div></div>
      <span className="sidebar-footer">С заботой о тебе <Heart size={12} /></span>
    </aside>
    <main id="home">
      <header className="topbar"><button className="icon-button mobile-menu" aria-label="Открыть меню" onClick={() => setMenu(true)}><Menu /></button><div className="search-wrap"><Search size={20} /><input aria-label="Поиск" placeholder="Найти рецепт, тренировку, продукт..." value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => { if (e.key === 'Escape') setQuery('') }} />{query && <div className="search-results">{results.length ? results.map((r, i) => <button key={i} onClick={() => { r.action(); setQuery('') }}><span>{r.label}</span><small>{r.type}</small></button>) : <p>Ничего не найдено. Попробуйте «овсяная».</p>}</div>}</div><div className="top-actions"><button className="icon-button notification-button" aria-label="Уведомления" onClick={() => setModal('notifications')}><Bell size={22} /><i /></button><span className="top-divider" /><button className="profile-button" onClick={() => setModal('profile')}><span className="avatar">{saved.name.slice(0, 1).toUpperCase()}</span><span><strong>{saved.name}</strong><small>На шаг ближе к себе</small></span><ChevronDown size={17} /></button></div></header>
      <div className="page-content"><div className="page-heading"><div><span className="eyebrow">ТВОЙ ЛИЧНЫЙ РИТМ</span><h1>Хороший день, чтобы начать <span>🌿</span></h1></div><span className="demo-label"><span />Демо-кабинет</span></div>
      {storageError && <p role="alert" className="storage-warning">Браузер не разрешил сохранение. Изменения останутся только до закрытия страницы.</p>}
      <div className="top-grid">
        <section className="hero"><div className="hero-content"><span className="eyebrow">ЗДОРОВЬЕ <i /> ПИТАНИЕ <i /> ДВИЖЕНИЕ <i /> БАЛАНС</span><h2>Твоё тело.<br />Каждый день.</h2><p>Сбалансированное питание, движение в удовольствие<br className="desktop-br" /> и маленькие привычки для больших перемен.</p><button className="primary-button" onClick={() => setModal('start')}>Начать сегодня <ArrowRight size={18} /></button></div><div className="hero-note">Лучшая версия тебя<br />начинается с заботы <Heart size={20} /></div><span className="hero-domain">TELO365.RU</span></section>
        <section className="card metrics"><SectionTitle title="Мои показатели" onClick={() => setModal('profile')} /><div className="weight-grid"><button className="weight-box" onClick={() => setModal('weight')}><span className="round-icon neutral"><Weight /></span><span><small>Текущий вес</small><strong>{number(saved.weight)} <em>кг</em></strong><span className="positive"><ArrowDownRight size={12} /> {number(Math.abs(73 - saved.weight))} кг от старта</span></span></button><button className="weight-box" onClick={() => setModal('profile')}><span className="round-icon green"><Flag /></span><span><small>Целевой вес</small><strong>{number(saved.target)} <em>кг</em></strong><span className="muted">{saved.weight > saved.target ? `Осталось ${number(saved.weight - saved.target)} кг` : 'Цель достигнута'}</span></span></button></div><div className="macro-grid">{[['Калории', '1 750', 'из 2 000 ккал', 'green', 87.5], ['Белки', '112 г', 'из 150 г', 'blue', 75], ['Жиры', '58 г', 'из 70 г', 'gold', 83], ['Углеводы', '180 г', 'из 250 г', 'purple', 72]].map(([label, val, goal, color, width]) => <div className="macro" key={label}><small>{label}</small><strong>{val}</strong><span>{goal}</span><div className="meter"><i className={`${color}`} style={{ width: `${width}%` }} /></div></div>)}</div><span className="metrics-foot"><span className="status-dot" /> Всё начинается с маленького шага</span></section>
      </div>
      <div className="dashboard-grid">
        <section className="card nutrition" id="nutrition"><SectionTitle title="Питание на сегодня" onClick={() => setModal('nutrition')} /><div className="nutrition-summary"><div className="calorie-ring"><Utensils size={19} /></div><div className="calorie-total"><strong>1 750</strong><small>из 2 000 ккал</small></div><div className="mini-macro blue"><span>Б</span><strong>112 г</strong></div><div className="mini-macro gold"><span>Ж</span><strong>58 г</strong></div><div className="mini-macro purple"><span>У</span><strong>180 г</strong></div></div><div className="meal-list">{meals.map((m, i) => <button className="meal-row" key={m.name} onClick={() => setModal(`meal-${i}`)}><img src={`/images/${m.image}.jpg`} alt={m.dish} /><span className="meal-description"><strong>{m.name}</strong><span>{m.dish}</span></span><span className="meal-numbers"><strong>{m.kcal} <small>ккал</small></strong><span>Б {m.p} <i>Ж {m.f}</i> У {m.c}</span></span></button>)}</div><button className="soft-button" onClick={() => setModal('nutrition')}>Открыть план питания <ArrowRight size={15} /></button></section>
        <section className="card workout" id="workout"><SectionTitle title="Тренировка"><span className="today-label"><span className="status-dot" /> Сегодня</span></SectionTitle><button className="workout-banner" onClick={() => setModal('workout')}><span className="workout-badge">ТВОЁ ВРЕМЯ ДЛЯ СЕБЯ</span><strong>Силовая тренировка<br />Всё тело</strong><span><Clock3 size={14} /> 45 минут <i /> <ChartNoAxesColumnIncreasing size={14} /> Средний</span></button><div className="exercise-list">{exercises.map(([name, count], i) => <button className="exercise-row" key={name} onClick={() => setModal('workout')}><span className={`exercise-icon exercise-${i}`}><Dumbbell size={23} /></span><span><strong>{name}</strong><small>{count}</small></span>{saved.workout.includes(i) && <Check className="positive" size={16} />}</button>)}</div><button className="soft-button" onClick={() => setModal('workout')}>Открыть план <ArrowRight size={15} /></button></section>
        <section className="card progress" id="progress"><SectionTitle title="Прогресс" onClick={() => setModal('weight')} /><div className="tabs" role="tablist" aria-label="Показатель прогресса">{['Вес', 'Объёмы', 'Фото', 'Калории'].map(t => <button role="tab" aria-selected={tab === t} className={tab === t ? 'selected' : ''} onClick={() => setTab(t)} key={t}>{t}</button>)}</div><div className="chart-area">{tab === 'Объёмы' || tab === 'Фото' ? <div className="chart-empty">{tab === 'Фото' ? <Camera size={32} /> : <Activity size={32} />}<strong>{tab === 'Фото' ? 'Твоя история в кадрах' : 'Больше, чем цифра на весах'}</strong><p>{tab === 'Фото' ? 'Фото появятся здесь после подключения личного кабинета.' : 'Дневник замеров появится в следующей версии.'}</p></div> : <><div className="chart-caption"><span>{tab === 'Вес' ? 'Вес, кг' : 'Калории, ккал'}</span><span>Последние 10 недель</span></div><svg className="weight-chart" viewBox="0 0 315 184" role="img" aria-label={tab === 'Вес' ? `Демонстрационный график веса от 73 до ${saved.weight} кг` : 'Демонстрационный график калорий за 10 недель'}><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6da067" stopOpacity=".22" /><stop offset="100%" stopColor="#6da067" stopOpacity="0" /></linearGradient></defs>{[0, 1, 2, 3, 4].map(i => <g key={i}><line x1="36" y1={22 + i * 32} x2="298" y2={22 + i * 32} stroke="#e9edef" /><text x="5" y={26 + i * 32}>{Math.round(chartMax - i * (chartMax - chartMin) / 4)}</text></g>)}{[0, 1, 2, 3, 4, 5].map(i => <line key={i} x1={38 + i * 51} y1="22" x2={38 + i * 51} y2="150" stroke="#f0f2f2" />)}<polygon points={`38,150 ${points} 292,150`} fill="url(#chart-fill)" /><polyline points={points} stroke="#518447" strokeWidth="2" fill="none" strokeLinejoin="round" />{chartValues.map((w, i) => <circle key={i} cx={38 + i * 25.4} cy={150 - (w - chartMin) / (chartMax - chartMin) * 128} r="4.1" fill="#4a853e" stroke="white" strokeWidth="1.6"><title>{number(w)} {tab === 'Вес' ? 'кг' : 'ккал'}</title></circle>)}{['Старт', '2 нед.', '4 нед.', '6 нед.', '8 нед.', 'Сейчас'].map((s, i) => <text key={s} x={38 + i * 51} y="176" textAnchor="middle">{s}</text>)}</svg></>}</div><button className="progress-callout" onClick={() => setModal('weight')}><span className="round-icon green"><ChartNoAxesColumnIncreasing size={23} /></span><span><strong>Ты на правильном пути!</strong><small>Каждый шаг имеет значение</small></span><ChevronRight size={19} /></button></section>
        <section className="card habits" id="habits"><SectionTitle title="Привычки"><span className="today-label">Сегодня</span></SectionTitle><div className="habit-list">{habitRows.map((h, i) => <button className="habit-row" key={h.name} aria-label={`${h.name}: ${saved.habits[i] ? 'выполнено' : 'не выполнено'}`} aria-pressed={saved.habits[i]} onClick={() => toggleHabit(i)}><span className={`round-icon ${h.color}`}><h.icon size={21} /></span><span><strong>{h.name}</strong><small>{h.text}</small></span><span className={`habit-check ${saved.habits[i] ? 'checked' : ''}`}>{saved.habits[i] && <Check size={13} />}</span></button>)}</div><div className="streak"><span className="flame"><Flame size={30} fill="#ffa928" /></span><span><small>Твой ритм сегодня</small><strong>{complete} из 5 привычек</strong><span>{complete === 5 ? 'Всё получилось. Отличный день!' : 'Забота о себе — каждый день'}</span></span><ChevronRight size={18} /></div></section>
      </div>
      <div className="bottom-grid"><section className="card shopping" id="shopping"><SectionTitle title="Покупки"><span className="week-label"><ShoppingBasket size={14} /> На эту неделю</span><button className="text-button" onClick={() => setModal('shopping')}>Все <ChevronRight size={15} /></button></SectionTitle><div className="shopping-content"><div className="grocery-preview"><div className="grocery-pictures">{groceries.map(([emoji, name]) => <button title={name} aria-label={name} key={name} onClick={() => setModal('shopping')}>{emoji}</button>)}</div><div className="shopping-caption"><Leaf size={14} /> Простые продукты. Сбалансированная неделя.</div></div><div className="shopping-total"><small>Примерная стоимость</small><strong>2 840 ₽</strong><button className="soft-button" onClick={() => setModal('shopping')}>Открыть список <ArrowRight size={14} /></button></div></div></section><section className="card photo-progress"><SectionTitle title="Маленькие победы" onClick={() => setModal('wins')} /><div className="wins-content"><div className="wins-icon"><Sprout size={45} /></div><div><span className="eyebrow">НЕ ТОЛЬКО ЦИФРЫ</span><h3>Больше энергии.<br />Больше тебя.</h3><p>Замечай, как меняется самочувствие.</p></div></div></section><section className="brand-card"><Logo /><p>Больше, чем фитнес.<br />Это образ жизни.</p><span>Сильнее с каждым днём <Heart size={14} /></span></section></div>
      <footer className="page-footer"><span>© {new Date().getFullYear()} TELO365 <i /> Твоё тело. Каждый день.</span><span>Демо: изменения сохраняются в этом браузере</span></footer></div>
    </main>
    {toast && <div className="toast" role="status"><Check size={18} />{toast}</div>}
    {modal && <Modal title={modal.startsWith('meal-') ? meals[Number(modal.slice(5))].name : ({ start: 'Начни с заботы о себе', nutrition: 'Твой план питания', workout: 'Силовая · Всё тело', weight: 'Записать вес', profile: 'Твой профиль', shopping: 'Покупки на неделю', notifications: 'Твои уведомления', wins: 'Твои маленькие победы' }[modal] || '')} close={() => setModal(null)}>
      {modal.startsWith('meal-') && (() => { const meal = meals[Number(modal.slice(5))]; return <div className="recipe"><img src={`/images/${meal.image}.jpg`} alt={meal.dish} /><h3>{meal.dish}</h3><div className="recipe-meta">{meal.kcal} ккал <span>Б {meal.p} г · Ж {meal.f} г · У {meal.c} г</span></div><h4>Что понадобится</h4><p>{meal.ingredients}</p><h4>Как приготовить</h4><p>{meal.recipe}</p><small className="muted">Пример блюда. Пищевая ценность ориентировочная.</small></div> })()}
      {modal === 'start' && <div className="onboarding"><div className="welcome-icon"><Sprout size={38} /></div><p>Не нужно менять всё сразу. Выбери один маленький шаг на сегодня.</p>{[['nutrition', 'Вкусно и сбалансированно поесть', Utensils], ['workout', 'Найти время для движения', Dumbbell], ['habits', 'Позаботиться о привычках', Heart]].map(([id, label, Icon]) => { const I = Icon as typeof Heart; return <button className="onboarding-option" key={id as string} onClick={() => { setModal(null); navigate(id as string) }}><I size={23} /><span>{label as string}</span><ArrowRight size={19} /></button> })}<small>Сейчас ты в демо-кабинете. Можно исследовать сайт и сохранять отметки в своём браузере.</small></div>}
      {modal === 'nutrition' && <div><p className="dialog-intro">Пример сбалансированного дня · 1 750 ккал</p>{meals.map((m, i) => <button className="plan-meal" onClick={() => setModal(`meal-${i}`)} key={m.name}><img src={`/images/${m.image}.jpg`} alt="" /><span><small>{m.name}</small><strong>{m.dish}</strong><span>{m.kcal} ккал</span></span><ChevronRight size={20} /></button>)}<p className="dialog-footnote">Демонстрационный план, без персонального расчёта.</p></div>}
      {modal === 'workout' && <div><p className="dialog-intro">45 минут · Гантели и коврик. Отмечай завершённые упражнения.</p>{exercises.map(([name, count, muscle], i) => <label className="checklist-row" key={name}><input type="checkbox" checked={saved.workout.includes(i)} onChange={() => setSaved(s => { const workout = s.workout.includes(i) ? s.workout.filter(x => x !== i) : [...s.workout, i]; return { ...s, workout, habits: s.habits.map((v, n) => n === 4 ? workout.length === 4 : v) } })} /><span><strong>{name}</strong><small>{count} · {muscle}</small></span></label>)}<div className="workout-completion">Завершено {saved.workout.length} из {exercises.length} упражнений</div></div>}
      {(modal === 'weight' || modal === 'profile') && <form className="profile-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); setSaved(s => ({ ...s, name: String(f.get('name') || s.name).trim() || s.name, weight: Number(f.get('weight')), target: Number(f.get('target') || s.target) })); setModal(null); setToast('Изменения сохранены в этом браузере') }}><p className="dialog-intro">Твой темп, твои цели. Данные демо-профиля хранятся только на этом устройстве.</p>{modal === 'profile' && <label>Как тебя зовут<input name="name" defaultValue={saved.name} required maxLength={40} /></label>}<label>Текущий вес, кг<input type="number" name="weight" min="30" max="300" step="0.1" defaultValue={saved.weight} required /></label>{modal === 'profile' && <label>Целевой вес, кг<input type="number" name="target" min="30" max="300" step="0.1" defaultValue={saved.target} required /></label>}<button className="primary-button" type="submit">Сохранить <Check size={17} /></button></form>}
      {modal === 'shopping' && <div><p className="dialog-intro">Всё необходимое для твоего плана. Отмечай продукты, которые уже в корзине.</p>{groceries.map(([emoji, name, amount], i) => <label className="checklist-row grocery-check" key={name}><input type="checkbox" checked={saved.checked.includes(i)} onChange={() => setSaved(s => ({ ...s, checked: s.checked.includes(i) ? s.checked.filter(x => x !== i) : [...s.checked, i] }))} /><span className="grocery-emoji">{emoji}</span><strong>{name}</strong><small>{amount}</small></label>)}<p className="dialog-footnote">Собрано {saved.checked.length} из {groceries.length} · 2 840 ₽ — пример для макета, без привязки к магазину.</p></div>}
      {modal === 'notifications' && <div className="empty-state"><Bell size={38} /><h3>Ты ничего не пропустила</h3><p>Здесь появятся напоминания о твоих планах и привычках. Пока можно отметить привычки прямо на главной.</p><button className="soft-button" onClick={() => { setModal(null); navigate('habits') }}>К привычкам <ArrowRight size={15} /></button></div>}
      {modal === 'wins' && <div className="empty-state"><Sprout size={44} /><h3>Прогресс бывает разным</h3><p>Проснулась бодрее, выбрала прогулку или нашла время для тренировки — всё это маленькие победы. Сегодня отмечено привычек: {complete} из 5.</p><button className="soft-button" onClick={() => { setModal(null); navigate('habits') }}>Отметить свою победу <Plus size={15} /></button></div>}
    </Modal>}
  </div>
}
